## Final Funcion at the end

In [1]:
import pandas as pd

In [2]:
import os

In [3]:
os.path.isfile('app.py')

False

In [4]:
files = os.listdir("C:/Users/Wajih/Work (DataScience)/CAPSTONE PROJECTS/Real Estate Project/Zameen.com/Scraping/datasets")

files = [i for i in files if i.startswith('final_data')]

In [5]:
files

['final_data_(0_to_5_rows).csv',
 'final_data_(1001_to_1300_rows).csv',
 'final_data_(1301_to_2000_rows).csv',
 'final_data_(2001_to_2500_rows).csv',
 'final_data_(2501_to_3000_rows).csv',
 'final_data_(3001_to_3300_rows).csv',
 'final_data_(3301_to_3800_rows).csv',
 'final_data_(3801_to_4500_rows).csv',
 'final_data_(4501_to_5500_rows).csv',
 'final_data_(501_to_1000_rows).csv',
 'final_data_(5501_to_6000_rows).csv',
 'final_data_(6001_to_8000_rows).csv',
 'final_data_(6_to_500_rows).csv',
 'final_data_(8001_to_8500_rows).csv',
 'final_data_(8501_to_9500_rows).csv',
 'final_data_(9501_to_10027_rows).csv']

In [6]:
original_df = pd.DataFrame()

In [7]:
#df1 = pd.read_csv('final_data_(0_to_300_rows).csv')
for fileName in files:
    temp = pd.read_csv(fileName)

    original_df = pd.concat((original_df,temp))

In [8]:
original_df

,Scraped_URL,Real Location,Type,Price,Bath(s),Area,Purpose,Bedroom(s),Added,Location,...,Amenities: Community Features,Amenities: Healthcare Recreational,Amenities: Nearby Locations and Other Facilities,Amenities: Other Facilities,Initial Amount,Monthly Installment,Remaining Installments,Balloon Payments,Total Balloon Payment,Possession Fee
0,https://www.zameen.com/Property/d_12_d-12_2_10...,"D-12/2, D-12",House,PKR12 Crore,7,10 Marla,For Sale,6,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.zameen.com/Property/d_12_d-12_1_4_...,"D-12/1, D-12",House,PKR5.2 Crore,4,4.4 Marla,For Sale,3,2 months ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.zameen.com/Property/d_12_d-12_4_4_...,"D-12/4, D-12",House,PKR4.3 Crore,5,4.4 Marla,For Sale,3,1 month ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.zameen.com/Property/d_12_d-12_1_5_...,"D-12/1, D-12",House,PKR5.75 Crore,6,5 Marla,For Sale,5,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.zameen.com/Property/bahria_enclave...,"Bahria Enclave - Sector H, Bahria Enclave",House,PKR2.7 Crore,4,5 Marla,For Sale,3,4 months ago,"Bahria Town, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,https://www.zameen.com/Property/g_13_g-13_4_50...,"G-13/4, G-13",House,PKR12 Crore,6,1 Kanal,For Sale,8,5 months ago,"G-13, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
422,https://www.zameen.com/Property/g_13_g-13_2_8_...,"G-13/2, G-13",House,PKR5.6 Crore,6,8 Marla,For Sale,5,5 months ago,"G-13, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Sauna, Jacuzzi, Other Healthca...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
423,https://www.zameen.com/Property/islamabad_g-13...,"G-13, Islamabad",House,PKR17 Crore,6,1 Kanal,For Sale,8,5 months ago,"G-13, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Gym, First...","Lawn or Garden, Sauna, Jacuzzi","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
424,https://www.zameen.com/Property/gulberg_greens...,"Gulberg Greens - Block B, Gulberg Greens",Flat,PKR1.1 Crore,1,2.4 Marla,For Sale,1,1 month ago,"Gulberg, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Sauna, Jacuzzi, Other Healthcare and Recreatio...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Laundry or ...",NaN,NaN,NaN,NaN,NaN,NaN
425,https://www.zameen.com/Property/mumtaz_city_mu...,"Mumtaz City - Chanab Block, Mumtaz City",House,PKR3.3 Crore,6,8 Marla,For Sale,4,2 months ago,"Mumtaz City, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...",NaN,"Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
def mergingDFs():
    import pandas as pd
    import os

    global files
    files = os.listdir("C:/Users/Wajih/Work (DataScience)/CAPSTONE PROJECTS/Real Estate Project/Zameen.com/Scraping/datasets")

    files = [i for i in files if i.startswith('final_data')]

    original_df = pd.DataFrame()

    for fileName in files:
        temp = pd.read_csv(fileName)
    
        original_df = pd.concat((original_df,temp),ignore_index=True)
        original_df.drop_duplicates(inplace=True)

    return original_df

In [11]:
mergingDFs()

,Scraped_URL,Real Location,Type,Price,Bath(s),Area,Purpose,Bedroom(s),Added,Location,...,Amenities: Community Features,Amenities: Healthcare Recreational,Amenities: Nearby Locations and Other Facilities,Amenities: Other Facilities,Initial Amount,Monthly Installment,Remaining Installments,Balloon Payments,Total Balloon Payment,Possession Fee
0,https://www.zameen.com/Property/d_12_d-12_2_10...,"D-12/2, D-12",House,PKR12 Crore,7,10 Marla,For Sale,6,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.zameen.com/Property/d_12_d-12_1_4_...,"D-12/1, D-12",House,PKR5.2 Crore,4,4.4 Marla,For Sale,3,2 months ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.zameen.com/Property/d_12_d-12_4_4_...,"D-12/4, D-12",House,PKR4.3 Crore,5,4.4 Marla,For Sale,3,1 month ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.zameen.com/Property/d_12_d-12_1_5_...,"D-12/1, D-12",House,PKR5.75 Crore,6,5 Marla,For Sale,5,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.zameen.com/Property/bahria_enclave...,"Bahria Enclave - Sector H, Bahria Enclave",House,PKR2.7 Crore,4,5 Marla,For Sale,3,4 months ago,"Bahria Town, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6478,https://www.zameen.com/Property/g_13_g-13_4_50...,"G-13/4, G-13",House,PKR12 Crore,6,1 Kanal,For Sale,8,5 months ago,"G-13, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
6479,https://www.zameen.com/Property/g_13_g-13_2_8_...,"G-13/2, G-13",House,PKR5.6 Crore,6,8 Marla,For Sale,5,5 months ago,"G-13, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Sauna, Jacuzzi, Other Healthca...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
6480,https://www.zameen.com/Property/islamabad_g-13...,"G-13, Islamabad",House,PKR17 Crore,6,1 Kanal,For Sale,8,5 months ago,"G-13, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Gym, First...","Lawn or Garden, Sauna, Jacuzzi","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
6481,https://www.zameen.com/Property/gulberg_greens...,"Gulberg Greens - Block B, Gulberg Greens",Flat,PKR1.1 Crore,1,2.4 Marla,For Sale,1,1 month ago,"Gulberg, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Sauna, Jacuzzi, Other Healthcare and Recreatio...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Laundry or ...",NaN,NaN,NaN,NaN,NaN,NaN
6482,https://www.zameen.com/Property/mumtaz_city_mu...,"Mumtaz City - Chanab Block, Mumtaz City",House,PKR3.3 Crore,6,8 Marla,For Sale,4,2 months ago,"Mumtaz City, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...",NaN,"Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df = mergingDFs()

In [13]:
df.head()

,Scraped_URL,Real Location,Type,Price,Bath(s),Area,Purpose,Bedroom(s),Added,Location,...,Amenities: Community Features,Amenities: Healthcare Recreational,Amenities: Nearby Locations and Other Facilities,Amenities: Other Facilities,Initial Amount,Monthly Installment,Remaining Installments,Balloon Payments,Total Balloon Payment,Possession Fee
0,https://www.zameen.com/Property/d_12_d-12_2_10...,"D-12/2, D-12",House,PKR12 Crore,7,10 Marla,For Sale,6,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.zameen.com/Property/d_12_d-12_1_4_...,"D-12/1, D-12",House,PKR5.2 Crore,4,4.4 Marla,For Sale,3,2 months ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.zameen.com/Property/d_12_d-12_4_4_...,"D-12/4, D-12",House,PKR4.3 Crore,5,4.4 Marla,For Sale,3,1 month ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.zameen.com/Property/d_12_d-12_1_5_...,"D-12/1, D-12",House,PKR5.75 Crore,6,5 Marla,For Sale,5,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.zameen.com/Property/bahria_enclave...,"Bahria Enclave - Sector H, Bahria Enclave",House,PKR2.7 Crore,4,5 Marla,For Sale,3,4 months ago,"Bahria Town, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df['Type'].value_counts()

Type
House         4603
Flat          1754
Farm House      90
Penthouse       14
Room             2
Name: count, dtype: int64

In [15]:
df.to_csv('C:/Users/Wajih/Work (DataScience)/CAPSTONE PROJECTS/Real Estate Project/Zameen.com/Scraping/datasets/zameen_new.csv')