## Final Funcion at the end

In [1]:
import pandas as pd

In [2]:
import os

In [3]:
os.path.isfile('app.py')

False

In [4]:
files = os.listdir("C:/Users/Wajih/Work (DataScience)/CAPSTONE PROJECTS/Real Estate Project/Zameen.com/Scraping/datasets")

files = [i for i in files if i.startswith('final_data')]

In [5]:
files

['final_data_(0_to_5_rows).csv',
 'final_data_(1001_to_1300_rows).csv',
 'final_data_(1301_to_2000_rows).csv',
 'final_data_(2001_to_2500_rows).csv',
 'final_data_(2501_to_3000_rows).csv',
 'final_data_(3001_to_3300_rows).csv',
 'final_data_(3301_to_3800_rows).csv',
 'final_data_(501_to_1000_rows).csv',
 'final_data_(6_to_500_rows).csv']

In [6]:
original_df = pd.DataFrame()

In [7]:
#df1 = pd.read_csv('final_data_(0_to_300_rows).csv')
for fileName in files:
    temp = pd.read_csv(fileName)

    original_df = pd.concat((original_df,temp))

In [8]:
original_df

,Scraped_URL,Real Location,Type,Price,Bath(s),Area,Purpose,Bedroom(s),Added,Location,...,Amenities: Main Features,Amenities: Rooms,Amenities: Business and Communication,Amenities: Community Features,Amenities: Healthcare Recreational,Amenities: Nearby Locations and Other Facilities,Amenities: Other Facilities,Initial Amount,Monthly Installment,Remaining Installments
0,https://www.zameen.com/Property/d_12_d-12_2_10...,"D-12/2, D-12",House,PKR12 Crore,7,10 Marla,For Sale,6,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year, Parking Spaces: 4, Double Glaze...","Bedrooms: 6, Bathrooms: 8, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN
1,https://www.zameen.com/Property/d_12_d-12_1_4_...,"D-12/1, D-12",House,PKR5.2 Crore,4,4.4 Marla,For Sale,3,2 months ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year, Parking Spaces: 3, Double Glaze...","Bedrooms: 3, Bathrooms: 4, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN
2,https://www.zameen.com/Property/d_12_d-12_4_4_...,"D-12/4, D-12",House,PKR4.3 Crore,5,4.4 Marla,For Sale,3,1 month ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year, Parking Spaces: 1, Double Glaze...","Bedrooms: 3, Bathrooms: 5, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
3,https://www.zameen.com/Property/d_12_d-12_1_5_...,"D-12/1, D-12",House,PKR5.75 Crore,6,5 Marla,For Sale,5,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year: 4, Parking Spaces: 2, Double Gl...","Bedrooms: 5, Bathrooms: 6, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
4,https://www.zameen.com/Property/bahria_enclave...,"Bahria Enclave - Sector H, Bahria Enclave",House,PKR2.7 Crore,4,5 Marla,For Sale,3,4 months ago,"Bahria Town, Islamabad, Islamabad Capital",...,"Built in year: 2025, Parking Spaces, Double Gl...","Bedrooms: 3, Bathrooms: 4, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,https://www.zameen.com/Property/islamabad_f-8_...,"F-8, Islamabad",House,PKR55 Crore,7,2.1 Kanal,For Sale,11,4 months ago,"F-8, Islamabad, Islamabad Capital",...,"Parking Spaces, Other Main Features","Bedrooms, Bathrooms, Drawing Room, Dining Room...","Broadband Internet Access, Satellite or Cable ...",Community Lawn or Garden,"Lawn or Garden, Swimming Pool","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff",NaN,NaN,NaN
350,https://www.zameen.com/Property/islamabad_f-8_...,"F-8, Islamabad",House,PKR25 Crore,6,1 Kanal,For Sale,5,4 months ago,"F-8, Islamabad, Islamabad Capital",...,"Built in year: 2020, Parking Spaces, Double Gl...","Bedrooms: 5, Bathrooms: 6, Servant Quarters, D...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
351,https://www.zameen.com/Property/islamabad_f-8_...,"F-8, Islamabad",House,PKR22 Crore,5,17.8 Marla,For Sale,5,3 months ago,"F-8, Islamabad, Islamabad Capital",...,"Parking Spaces, Double Glazed Windows, Central...","Bedrooms: 5, Bathrooms: 5, Servant Quarters, D...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Other Healthcare and Recreatio...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
352,https://www.zameen.com/Property/islamabad_f-7_...,"F-7, Islamabad",House,PKR30 Crore,5,1.3 Kanal,For Sale,5,2 weeks ago,"F-7, Islamabad, Islamabad Capital",...,"Built in year: 2000, Parking Spaces: 5, Double...","Bedrooms: 5, Bathrooms: 5, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Sauna, Jacuzzi, Other Healthca...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
353,https://www.zameen.com/Property/top_city_1_top...,"Top City 1 - Block D, Top City 1",House,PKR5.5 Crore,6,10 Marla,For Sale,6,2 weeks ago,"Top City 1, Islamabad, Islamabad Capital",...,"Built in year: 2020, Parking Spaces: 3, Double...","Bedrooms: 6, Bathrooms: 6, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Gym, First...","Lawn or Garden, Other Healthcare and Recreatio...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Other Facil...",NaN,NaN,NaN

In [10]:
def mergingDFs():
    import pandas as pd
    import os

    global files
    files = os.listdir("C:/Users/Wajih/Work (DataScience)/CAPSTONE PROJECTS/Real Estate Project/Zameen.com/Scraping/datasets")

    files = [i for i in files if i.startswith('final_data')]

    original_df = pd.DataFrame()

    for fileName in files:
        temp = pd.read_csv(fileName)
    
        original_df = pd.concat((original_df,temp),ignore_index=True)
        original_df.drop_duplicates(inplace=True)

    return original_df

In [11]:
mergingDFs()

,Scraped_URL,Real Location,Type,Price,Bath(s),Area,Purpose,Bedroom(s),Added,Location,...,Amenities: Main Features,Amenities: Rooms,Amenities: Business and Communication,Amenities: Community Features,Amenities: Healthcare Recreational,Amenities: Nearby Locations and Other Facilities,Amenities: Other Facilities,Initial Amount,Monthly Installment,Remaining Installments
0,https://www.zameen.com/Property/d_12_d-12_2_10...,"D-12/2, D-12",House,PKR12 Crore,7,10 Marla,For Sale,6,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year, Parking Spaces: 4, Double Glaze...","Bedrooms: 6, Bathrooms: 8, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN
1,https://www.zameen.com/Property/d_12_d-12_1_4_...,"D-12/1, D-12",House,PKR5.2 Crore,4,4.4 Marla,For Sale,3,2 months ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year, Parking Spaces: 3, Double Glaze...","Bedrooms: 3, Bathrooms: 4, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN
2,https://www.zameen.com/Property/d_12_d-12_4_4_...,"D-12/4, D-12",House,PKR4.3 Crore,5,4.4 Marla,For Sale,3,1 month ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year, Parking Spaces: 1, Double Glaze...","Bedrooms: 3, Bathrooms: 5, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
3,https://www.zameen.com/Property/d_12_d-12_1_5_...,"D-12/1, D-12",House,PKR5.75 Crore,6,5 Marla,For Sale,5,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year: 4, Parking Spaces: 2, Double Gl...","Bedrooms: 5, Bathrooms: 6, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
4,https://www.zameen.com/Property/bahria_enclave...,"Bahria Enclave - Sector H, Bahria Enclave",House,PKR2.7 Crore,4,5 Marla,For Sale,3,4 months ago,"Bahria Town, Islamabad, Islamabad Capital",...,"Built in year: 2025, Parking Spaces, Double Gl...","Bedrooms: 3, Bathrooms: 4, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2682,https://www.zameen.com/Property/islamabad_f-8_...,"F-8, Islamabad",House,PKR55 Crore,7,2.1 Kanal,For Sale,11,4 months ago,"F-8, Islamabad, Islamabad Capital",...,"Parking Spaces, Other Main Features","Bedrooms, Bathrooms, Drawing Room, Dining Room...","Broadband Internet Access, Satellite or Cable ...",Community Lawn or Garden,"Lawn or Garden, Swimming Pool","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff",NaN,NaN,NaN
2683,https://www.zameen.com/Property/islamabad_f-8_...,"F-8, Islamabad",House,PKR25 Crore,6,1 Kanal,For Sale,5,4 months ago,"F-8, Islamabad, Islamabad Capital",...,"Built in year: 2020, Parking Spaces, Double Gl...","Bedrooms: 5, Bathrooms: 6, Servant Quarters, D...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
2684,https://www.zameen.com/Property/islamabad_f-8_...,"F-8, Islamabad",House,PKR22 Crore,5,17.8 Marla,For Sale,5,3 months ago,"F-8, Islamabad, Islamabad Capital",...,"Parking Spaces, Double Glazed Windows, Central...","Bedrooms: 5, Bathrooms: 5, Servant Quarters, D...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Other Healthcare and Recreatio...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
2685,https://www.zameen.com/Property/islamabad_f-7_...,"F-7, Islamabad",House,PKR30 Crore,5,1.3 Kanal,For Sale,5,2 weeks ago,"F-7, Islamabad, Islamabad Capital",...,"Built in year: 2000, Parking Spaces: 5, Double...","Bedrooms: 5, Bathrooms: 5, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Sauna, Jacuzzi, Other Healthca...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
2686,https://www.zameen.com/Property/top_city_1_top...,"Top City 1 - Block D, Top City 1",House,PKR5.5 Crore,6,10 Marla,For Sale,6,2 weeks ago,"Top City 1, Islamabad, Islamabad Capital",...,"Built in year: 2020, Parking Spaces: 3, Double...","Bedrooms: 6, Bathrooms: 6, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Gym, First...","Lawn or Garden, Other Healthcare and Recreatio...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Other Facil...",NaN,NaN,NaN

In [12]:
df = mergingDFs()

In [13]:
df.head()

,Scraped_URL,Real Location,Type,Price,Bath(s),Area,Purpose,Bedroom(s),Added,Location,...,Amenities: Main Features,Amenities: Rooms,Amenities: Business and Communication,Amenities: Community Features,Amenities: Healthcare Recreational,Amenities: Nearby Locations and Other Facilities,Amenities: Other Facilities,Initial Amount,Monthly Installment,Remaining Installments
0,https://www.zameen.com/Property/d_12_d-12_2_10...,"D-12/2, D-12",House,PKR12 Crore,7,10 Marla,For Sale,6,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year, Parking Spaces: 4, Double Glaze...","Bedrooms: 6, Bathrooms: 8, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN
1,https://www.zameen.com/Property/d_12_d-12_1_4_...,"D-12/1, D-12",House,PKR5.2 Crore,4,4.4 Marla,For Sale,3,2 months ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year, Parking Spaces: 3, Double Glaze...","Bedrooms: 3, Bathrooms: 4, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN
2,https://www.zameen.com/Property/d_12_d-12_4_4_...,"D-12/4, D-12",House,PKR4.3 Crore,5,4.4 Marla,For Sale,3,1 month ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year, Parking Spaces: 1, Double Glaze...","Bedrooms: 3, Bathrooms: 5, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
3,https://www.zameen.com/Property/d_12_d-12_1_5_...,"D-12/1, D-12",House,PKR5.75 Crore,6,5 Marla,For Sale,5,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year: 4, Parking Spaces: 2, Double Gl...","Bedrooms: 5, Bathrooms: 6, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
4,https://www.zameen.com/Property/bahria_enclave...,"Bahria Enclave - Sector H, Bahria Enclave",House,PKR2.7 Crore,4,5 Marla,For Sale,3,4 months ago,"Bahria Town, Islamabad, Islamabad Capital",...,"Built in year: 2025, Parking Spaces, Double Gl...","Bedrooms: 3, Bathrooms: 4, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN

In [14]:
df.to_csv('C:/Users/Wajih/Work (DataScience)/CAPSTONE PROJECTS/Real Estate Project/Zameen.com/Scraping/datasets/zameen_new.csv')