In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('zameen.csv',index_col=0)

In [3]:
df.head()

,Scraped_URL,Type,Price,Bath(s),Area,Purpose,Bedroom(s),Added,Location,Description,Amenities: Main Features,Amenities: Rooms,Amenities: Business and Communication,Amenities: Community Features,Amenities: Healthcare Recreational,Amenities: Nearby Locations and Other Facilities,Amenities: Other Facilities,Initial Amount,Monthly Installment,Remaining Installments
0,https://www.zameen.com/Property/d_12_d-12_2_10...,House,PKR12 Crore,7,10 Marla,For Sale,6,2 days ago,"D-12, Islamabad, Islamabad Capital",10 MARLA LUXXARY BRAND NEW PARK FACE AVAILABLE...,"Built in year, Parking Spaces: 4, Double Glaze...","Bedrooms: 6, Bathrooms: 8, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN
1,https://www.zameen.com/Property/d_12_d-12_4_4_...,House,PKR4.3 Crore,5,4.4 Marla,For Sale,3,2 days ago,"D-12, Islamabad, Islamabad Capital",4.44 Marla Single Unit Luxury House with Open ...,"Built in year, Parking Spaces: 1, Double Glaze...","Bedrooms: 3, Bathrooms: 5, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN
2,https://www.zameen.com/Property/d_12_d-12_1_5_...,House,PKR5.75 Crore,6,5 Marla,For Sale,5,2 days ago,"D-12, Islamabad, Islamabad Capital",5 Marla Double Unit Front-Open 50 ft street Ho...,"Built in year: 4, Parking Spaces: 2, Double Gl...","Bedrooms: 5, Bathrooms: 6, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
3,https://www.zameen.com/Property/bahria_enclave...,House,PKR2.7 Crore,4,5 Marla,For Sale,3,5 days ago,"Bahria Town, Islamabad, Islamabad Capital",Brand-New Designer House for Sale in Bahria En...,"Built in year: 2025, Parking Spaces, Double Gl...","Bedrooms: 3, Bathrooms: 4, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
4,https://www.zameen.com/Property/fechs_jinnah_g...,House,PKR3 Crore,6,7 Marla,For Sale,5,2 weeks ago,"FECHS, Islamabad, Islamabad Capital",Now We Found A Beautiful And Luxury House In J...,"Built in year, Parking Spaces, Double Glazed W...","Bedrooms: 3, Bathrooms: 3, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2879 entries, 0 to 2879
Data columns (total 20 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Scraped_URL                                       2879 non-null   object
 1   Type                                              2879 non-null   object
 2   Price                                             2879 non-null   object
 3   Bath(s)                                           2879 non-null   object
 4   Area                                              2879 non-null   object
 5   Purpose                                           2879 non-null   object
 6   Bedroom(s)                                        2879 non-null   object
 7   Added                                             2879 non-null   object
 8   Location                                          2879 non-null   object
 9   Description                                       2879 non-null   object
 10  Amenities: Main Features                          2695 non-null   object
 11  Amenities: Rooms                                  2634 non-null   object
 12  Amenities: Business and Communication             2528 non-null   object
 13  Amenities: Community Features                     2521 non-null   object
 14  Amenities: Healthcare Recreational                2283 non-null   object
 15  Amenities: Nearby Locations and Other Facilities  2693 non-null   object
 16  Amenities: Other Facilities                       2495 non-null   object
 17  Initial Amount                                    83 non-null     object
 18  Monthly Installment                               83 non-null     object
 19  Remaining Installments                            83 non-null     object
dtypes: object(20)
memory usage: 472.3+ KB

In [5]:
df.isnull().sum()

Scraped_URL                                            0
Type                                                   0
Price                                                  0
Bath(s)                                                0
Area                                                   0
Purpose                                                0
Bedroom(s)                                             0
Added                                                  0
Location                                               0
Description                                            0
Amenities: Main Features                             184
Amenities: Rooms                                     245
Amenities: Business and Communication                351
Amenities: Community Features                        358
Amenities: Healthcare Recreational                   596
Amenities: Nearby Locations and Other Facilities     186
Amenities: Other Facilities                          384
Initial Amount                                      2796
Monthly Installment                                 2796
Remaining Installments                              2796
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
cols_to_remove = ['Scraped_URL','Purpose','Added','Initial Amount','Monthly Installment','Remaining Installments']

In [8]:
df.drop(columns=cols_to_remove,inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2879 entries, 0 to 2879
Data columns (total 14 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Type                                              2879 non-null   object
 1   Price                                             2879 non-null   object
 2   Bath(s)                                           2879 non-null   object
 3   Area                                              2879 non-null   object
 4   Bedroom(s)                                        2879 non-null   object
 5   Location                                          2879 non-null   object
 6   Description                                       2879 non-null   object
 7   Amenities: Main Features                          2695 non-null   object
 8   Amenities: Rooms                                  2634 non-null   object
 9   Amenities: Business and Communication             2528 non-null   object
 10  Amenities: Community Features                     2521 non-null   object
 11  Amenities: Healthcare Recreational                2283 non-null   object
 12  Amenities: Nearby Locations and Other Facilities  2693 non-null   object
 13  Amenities: Other Facilities                       2495 non-null   object
dtypes: object(14)
memory usage: 337.4+ KB

In [10]:
df.duplicated().sum()

np.int64(6)

### Price
Selecting a common unit

In [11]:
df['Price'].str.split(' ').str.get(1).value_counts()

Price
Crore    2583
Lakh      261
Arab       35
Name: count, dtype: int64

In [12]:
df['Price'].str.split(' ').str.get(0).str[3:].astype('float')

0       12.00
1        4.30
2        5.75
3        2.70
4        3.00
        ...
2875    83.00
2876    75.00
2877     2.40
2878     7.90
2879    16.00
Name: Price, Length: 2879, dtype: float64

In [13]:
def Price_to_Cr(series):
    unit = series.strip().split(' ')[1]
    price = float(series.strip().split(' ')[0][3:])
    if (unit =='Lakh'):
        price = price / 100
    elif (unit =='Arab'):
        price = price * 100

    series = price
    return series

In [14]:
df['Price'].apply(Price_to_Cr)

0       12.00
1        4.30
2        5.75
3        2.70
4        3.00
        ...
2875     0.83
2876     0.75
2877     2.40
2878     7.90
2879    16.00
Name: Price, Length: 2879, dtype: float64

In [15]:
df['Price'] = df['Price'].apply(Price_to_Cr)

In [16]:
df['Price'].sample(10)

1014    19.50
1391     0.71
321      2.50
1825    24.00
2496     8.50
2861    30.00
34      10.75
999     13.50
1475     2.15
2460     0.75
Name: Price, dtype: float64

In [69]:
df.rename(columns={"Price":'Price(Cr)'},inplace=True)

### Bath(s)
There is '-' category,<br>We can fill it from 'Amenities: Room'

In [17]:
df['Bath(s)'].value_counts()

Bath(s)
6     959
5     412
2     320
4     288
3     271
7     235
1     213
-     178
10      2
9       1
Name: count, dtype: int64

In [28]:
df[df['Bath(s)'] == '-']['Amenities: Rooms'].str.split(',').str.get(1).str.split(':').str.get(0).value_counts()

Amenities: Rooms
Bathrooms       126
Dining Room      18
Drawing Room      1
Other Rooms       1
Name: count, dtype: int64

In [32]:
df[df['Bath(s)'] == '-']['Amenities: Rooms'].sample(5)

1860                     Servant Quarters: 1, Other Rooms
392     Bedrooms, Bathrooms, Servant Quarters, Drawing...
243     Bedrooms: 5, Bathrooms: 6, Servant Quarters: 1...
2526                            Drawing Room, Dining Room
1072    Bedrooms: 9, Bathrooms: 9, Servant Quarters: 3...
Name: Amenities: Rooms, dtype: object

<br>
**Will remove those rows where you cannot fill the 'Bath(s)' information from 'Amenities: Room'

In [51]:
temp = df[df['Bath(s)'] == '-']['Amenities: Rooms'].str.split('Bathrooms').str.get(1).str.split(',').str.get(0).str.strip()
empty_idxs = temp[temp==''].index

In [55]:
temp.sample(5)

1683    : 5
2244    : 5
2363
472     : 6
1931
Name: Amenities: Rooms, dtype: object

In [56]:
empty_idxs

Index([392, 443, 1457, 1931, 2363], dtype='int64')

In [57]:
df.drop(index=empty_idxs,inplace=True)

In [58]:
df.shape[0]

2874

### Area
Converting Kanal to Marla. <br>
1 Kanal = 20 Marla

In [60]:
df['Area'].sample(5)

2334    10 Marla
2680    10 Marla
2541     1 Kanal
2251    10 Marla
885      6 Marla
Name: Area, dtype: object

In [66]:
# No other unit for Area
df['Area'].str.split().str.get(1).value_counts()

Area
Marla    2027
Kanal     847
Name: count, dtype: int64

,Type,Price(Cr),Bath(s),Area,Bedroom(s),Location,Description,Amenities: Main Features,Amenities: Rooms,Amenities: Business and Communication,Amenities: Community Features,Amenities: Healthcare Recreational,Amenities: Nearby Locations and Other Facilities,Amenities: Other Facilities
1651,Flat,0.23,1,1.1 Marla,-,"E-16, Islamabad, Islamabad Capital","Tower-X, Main Boulevard, Sector E-16/3 CDECHS ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1144,Flat,0.26,1,1.1 Marla,-,"Soan Garden, Islamabad, Islamabad Capital",In this add we discussed about Gross 250 sqft ...,"Built in year: 2024, Parking Spaces: 5, Lobby ...","Bedrooms: 1, Bathrooms: 1, Drawing Room, Dinin...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Sauna, Jacuzzi, Other Healthcare and Recreatio...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ..."
1815,Flat,0.29,-,1 Marla,-,"Top City 1, Islamabad, Islamabad Capital",studio apartment for sale in top city 1 Islama...,"Lobby in Building, Double Glazed Windows, Cent...","Drawing Room, Dining Room, Study Room, Prayer ...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, First Aid or Medical...","Sauna, Jacuzzi","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities"
1020,Flat,0.35,2,2.3 Marla,2,"H-13, Islamabad, Islamabad Capital",solid building Fully ventilation Apartment Siz...,"Flooring, Floor: 3, Elevators: 6","Bedrooms: 2, Bathrooms: 2, Kitchens: 1",NaN,NaN,NaN,NaN,NaN
2017,Flat,0.35,1,1.3 Marla,-,"Gulberg, Islamabad, Islamabad Capital",Studio Apartment for Sale in Gulberg Rasidenci...,"Built in year: 2024, Parking Spaces: 2, Lobby ...","Bedrooms: 1, Bathrooms: 1, Servant Quarters, D...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Sauna, Jacuzzi, Other Healthcare and Recreatio...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Laundry or ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1628,House,180.00,-,4 Kanal,-,"F-6, Islamabad, Islamabad Capital",#Top Location #Hill Road #Corner #Extra land #...,"Built in year: 2025, Parking Spaces: 2, Double...","Bedrooms: 5, Bathrooms: 6, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Gym, First...","Lawn or Garden, Sauna, Other Healthcare and Re...","Nearby Schools, Nearby Hospitals, Nearby Shopp...",NaN
1857,House,180.00,5,4 Kanal,7,"F-7, Islamabad, Islamabad Capital",Marriott Estate And Builders Offer a Ideal Hou...,"Built in year: 2009, Parking Spaces: 7, Double...","Bedrooms: 4, Bathrooms: 5, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Gym, First...","Lawn or Garden, Sauna, Jacuzzi","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ..."
2408,House,200.00,6,4 Kanal,6,"F-6, Islamabad, Islamabad Capital",f6-3 Most Desirable Location with swimming poo...,"Built in year: 2023, Parking Spaces, Double Gl...","Bedrooms: 2, Bathrooms: 6, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities"
291,House,235.00,6,3.9 Kanal,9,"F-6, Islamabad, Islamabad Capital",F-6/3 Beautiful House 100 % Out of Market Deal...,"Built in year: 2023, Parking Spaces: 4, Double...","Bedrooms: 9, Bathrooms: 10, Servant Quarters: ...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ..."
868,House,400.00,-,4 Kanal,8,"F-7, Islamabad, Islamabad Capital",Marriott Estate And Builders Offer a Ideal Hou...,"Built in year: 20223, Parking Spaces: 7, Doubl...","Bedrooms: 6, Bathrooms: 7, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ..."

In [73]:
def Areaunitconverter(series):
    unit = series.split()[1].strip()
    no = float(series.split()[0])
    if unit == 'Kanal':
        no *= 20

    return no

In [80]:
df['Area'].apply(Areaunitconverter).tail(5)

2875     5.0
2876     5.0
2877     5.0
2878     8.0
2879    22.0
Name: Area, dtype: float64

In [81]:
df['Area'].tail(5)

2875      5 Marla
2876      5 Marla
2877      5 Marla
2878      8 Marla
2879    1.1 Kanal
Name: Area, dtype: object

In [82]:
df['Area'] = df['Area'].apply(Areaunitconverter)

In [86]:
df.rename(columns={'Area':'Area(Marla)'},inplace=True)

### Location
Remove the part 'Islamabad, Islmabad Capital' since it is the same every where.

In [87]:
df['Location']

0              D-12, Islamabad, Islamabad Capital
1              D-12, Islamabad, Islamabad Capital
2              D-12, Islamabad, Islamabad Capital
3       Bahria Town, Islamabad, Islamabad Capital
4             FECHS, Islamabad, Islamabad Capital
                          ...
2875    DHA Defence, Islamabad, Islamabad Capital
2876    DHA Defence, Islamabad, Islamabad Capital
2877           H-13, Islamabad, Islamabad Capital
2878           E-11, Islamabad, Islamabad Capital
2879           G-11, Islamabad, Islamabad Capital
Name: Location, Length: 2874, dtype: object

In [107]:
df['Location'].str.split(',',n=1).str.get(1).value_counts()

Location
Islamabad, Islamabad Capital    2874
Name: count, dtype: int64

In [110]:
pd.set_option('display.max_rows', None)

In [112]:
df['Location'].str.split(',').str.get(0).value_counts().sort_index()

Location
Abdullah Garden                     1
Airport Enclave                     3
Alipur Farash                       1
Arsalan Town                        2
B-17                              234
Bahria Town                       184
Bani Gala                         100
Bhara kahu                          8
Blue Area                           7
Burma Town                          2
C-18                                1
CBR Town                           12
Chak Shahzad                       12
Constitution Avenue                 2
D-12                               89
D-17                               29
DHA Defence                       533
Diplomatic Enclave                 12
E-11                               72
E-16                                4
E-17                                1
E-18                                9
E-7                                22
Emaar Canyon Views                  8
F-10                               86
F-11                               86
F-17                               11
F-6                                69
F-7                                66
F-8                                96
FECHS                              50
Faisal Hills                       16
Faisal Town - F-18                 64
G-10                               36
G-11                               55
G-12                                1
G-13                              100
G-14                               21
G-15                               27
G-16                                6
G-6                                10
G-7                                 1
G-8                                 5
G-9                                28
GT Road                            12
Ghauri Town                         8
Green Avenue                        1
Gulberg                           137
H-12                                1
H-13                               31
I-10                               15
I-11                               12
I-12                               19
I-13                                1
I-14                               13
I-16                               13
I-8                                48
I-9                                 1
Islamabad - Murree Expressway       1
Islamabad Expressway               12
Jhangi Syedan                       1
Karakoram Diplomatic Enclave       10
Kashmir Highway                    31
Khanna Pul                         13
Korang Town                         4
Kuri Road                           8
Lehtrar Road                        3
Margalla Town                       1
Multi Residencia & Orchards         2
Mumtaz City                        28
National Police Foundation          1
National Police Foundation O-9      3
Naval Anchorage                    21
New Blue Area                       5
OPF Valley                          1
PAF Tarnol                          1
PECHS                               2
PWD Housing Scheme                 19
Pakistan Town                       3
Park Enclave                        6
Park Road                           1
Park View City                     15
Phulgran                            1
Pir Sohawa                          2
Rawal Enclave                       1
River Garden                        4
Sarai Kharbuza                      1
Sehala Farm House                   1
Shah Allah Ditta                    1
Shehzad Town                        1
Simly Dam Road                      1
Soan Garden                        49
Taramrri                            1
Tarlai                              3
Tarnol                              4
Top City 1                        110
University Town                     2
Zaraj Housing Scheme                6
Name: count, dtype: int64

In [118]:
df['Location'] = df['Location'].str.split(',').str.get(0).str.strip()

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2874 entries, 0 to 2879
Data columns (total 14 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Type                                              2874 non-null   object
 1   Price(Cr)                                         2874 non-null   float64
 2   Bath(s)                                           2874 non-null   object
 3   Area(Marla)                                       2874 non-null   float64
 4   Bedroom(s)                                        2874 non-null   object
 5   Location                                          2874 non-null   object
 6   Description                                       2874 non-null   object
 7   Amenities: Main Features                          2690 non-null   object
 8   Amenities: Rooms                                  2629 non-null   object
 9   Amenities: Business and Communication             2523 non-null   object
 10  Amenities: Community Features                     2516 non-null   object
 11  Amenities: Healthcare Recreational                2278 non-null   object
 12  Amenities: Nearby Locations and Other Facilities  2688 non-null   object
 13  Amenities: Other Facilities                       2491 non-null   object
dtypes: float64(2), object(12)
memory usage: 401.3+ KB

In [124]:
df['Amenities: Rooms'].iloc[0]

'Bedrooms: 6, Bathrooms: 8, Servant Quarters: 2, Drawing Room, Dining Room, Kitchens: 2, Study Room, Prayer Room, Powder Room, Gym, Store Rooms: 1, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms'

In [123]:
df['Amenities: Main Features'].iloc[1]

'Built in year, Parking Spaces: 1, Double Glazed Windows, Central Air Conditioning, Central Heating, Flooring, Electricity Backup, Waste Disposal, Floors: 2, Other Main Features'

In [127]:
df.to_csv('zameen_cleaned_v1.csv')

In [128]:
df.duplicated().sum()

np.int64(6)