In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('zameen_new.csv',index_col=0)

In [3]:
df.head()

,Scraped_URL,Real Location,Type,Price,Bath(s),Area,Purpose,Bedroom(s),Added,Location,...,Amenities: Main Features,Amenities: Rooms,Amenities: Business and Communication,Amenities: Community Features,Amenities: Healthcare Recreational,Amenities: Nearby Locations and Other Facilities,Amenities: Other Facilities,Initial Amount,Monthly Installment,Remaining Installments
0,https://www.zameen.com/Property/d_12_d-12_2_10...,"D-12/2, D-12",House,PKR12 Crore,7,10 Marla,For Sale,6,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year, Parking Spaces: 4, Double Glaze...","Bedrooms: 6, Bathrooms: 8, Servant Quarters: 2...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN
1,https://www.zameen.com/Property/d_12_d-12_1_4_...,"D-12/1, D-12",House,PKR5.2 Crore,4,4.4 Marla,For Sale,3,2 months ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year, Parking Spaces: 3, Double Glaze...","Bedrooms: 3, Bathrooms: 4, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN
2,https://www.zameen.com/Property/d_12_d-12_4_4_...,"D-12/4, D-12",House,PKR4.3 Crore,5,4.4 Marla,For Sale,3,1 month ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year, Parking Spaces: 1, Double Glaze...","Bedrooms: 3, Bathrooms: 5, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
3,https://www.zameen.com/Property/d_12_d-12_1_5_...,"D-12/1, D-12",House,PKR5.75 Crore,6,5 Marla,For Sale,5,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Built in year: 4, Parking Spaces: 2, Double Gl...","Bedrooms: 5, Bathrooms: 6, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN
4,https://www.zameen.com/Property/bahria_enclave...,"Bahria Enclave - Sector H, Bahria Enclave",House,PKR2.7 Crore,4,5 Marla,For Sale,3,4 months ago,"Bahria Town, Islamabad, Islamabad Capital",...,"Built in year: 2025, Parking Spaces, Double Gl...","Bedrooms: 3, Bathrooms: 4, Servant Quarters: 1...","Broadband Internet Access, Satellite or Cable ...","Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
Index: 2685 entries, 0 to 2686
Data columns (total 21 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Scraped_URL                                       2685 non-null   str
 1   Real Location                                     2685 non-null   str
 2   Type                                              2685 non-null   str
 3   Price                                             2685 non-null   str
 4   Bath(s)                                           2685 non-null   str
 5   Area                                              2685 non-null   str
 6   Purpose                                           2685 non-null   str
 7   Bedroom(s)                                        2685 non-null   str
 8   Added                                             2685 non-null   str
 9   Location                                          2685 non-null   str
 10  Description                                       2685 non-null   str
 11  Amenities: Main Features                          2554 non-null   str
 12  Amenities: Rooms                                  2478 non-null   str
 13  Amenities: Business and Communication             2428 non-null   str
 14  Amenities: Community Features                     2412 non-null   str
 15  Amenities: Healthcare Recreational                2181 non-null   str
 16  Amenities: Nearby Locations and Other Facilities  2572 non-null   str
 17  Amenities: Other Facilities                       2395 non-null   str
 18  Initial Amount                                    77 non-null     str
 19  Monthly Installment                               77 non-null     str
 20  Remaining Installments                            77 non-null     str
dtypes: str(21)
memory usage: 4.8 MB

In [5]:
df.isnull().sum()

Scraped_URL                                            0
Real Location                                          0
Type                                                   0
Price                                                  0
Bath(s)                                                0
Area                                                   0
Purpose                                                0
Bedroom(s)                                             0
Added                                                  0
Location                                               0
Description                                            0
Amenities: Main Features                             131
Amenities: Rooms                                     207
Amenities: Business and Communication                257
Amenities: Community Features                        273
Amenities: Healthcare Recreational                   504
Amenities: Nearby Locations and Other Facilities     113
Amenities: Other Facilities                          290
Initial Amount                                      2608
Monthly Installment                                 2608
Remaining Installments                              2608
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
cols_to_remove = ['Scraped_URL','Purpose','Added','Initial Amount','Monthly Installment','Remaining Installments']

In [8]:
df.drop(columns=cols_to_remove,inplace=True)

In [9]:
df.info()

<class 'pandas.DataFrame'>
Index: 2685 entries, 0 to 2686
Data columns (total 15 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Real Location                                     2685 non-null   str
 1   Type                                              2685 non-null   str
 2   Price                                             2685 non-null   str
 3   Bath(s)                                           2685 non-null   str
 4   Area                                              2685 non-null   str
 5   Bedroom(s)                                        2685 non-null   str
 6   Location                                          2685 non-null   str
 7   Description                                       2685 non-null   str
 8   Amenities: Main Features                          2554 non-null   str
 9   Amenities: Rooms                                  2478 non-null   str
 10  Amenities: Business and Communication             2428 non-null   str
 11  Amenities: Community Features                     2412 non-null   str
 12  Amenities: Healthcare Recreational                2181 non-null   str
 13  Amenities: Nearby Locations and Other Facilities  2572 non-null   str
 14  Amenities: Other Facilities                       2395 non-null   str
dtypes: str(15)
memory usage: 4.2 MB

In [10]:
df.duplicated().sum()

np.int64(5)

In [12]:
df['Real Location'].sample(10)

2533       Diamond Mall & Residency, Gulberg Greens
749                                 G-11, Islamabad
1737                      Eighteen, Kashmir Highway
2553    Smama Star Mall & Residency, Gulberg Greens
678       Bahria Enclave - Sector G, Bahria Enclave
1221                                 F-6, Islamabad
956                      Faisal Margalla City, B-17
656                   Faisal Town - F-18, Islamabad
2195                 Constitution Avenue, Islamabad
1969               DHA Defence Phase 2, DHA Defence
Name: Real Location, dtype: str

In [19]:
with pd.option_context('display.max_rows', None):
    print(df['Real Location'].str.split(',').str.get(0).value_counts())

Real Location
DHA Defence Phase 2                          172
Bani Gala                                     90
G-13                                          84
D-12                                          74
B-17                                          67
Bahria Enclave                                61
Top City 1                                    54
F-8                                           47
MPCHS - Block F                               44
F-7                                           44
Bahria Enclave - Sector C1                    42
Bahria Enclave - Sector N                     41
MPCHS - Multi Gardens                         40
F-6                                           39
Gulberg Greens                                34
The Centaurus                                 31
F-11                                          29
Jinnah Gardens                                26
Faisal Margalla City                          26
Eighteen                                      25
Top City 1 - Block A                          24
D-12/4                                        23
E-11                                          23
Diplomatic Enclave                            21
Faisal Town - F-18                            21
MPCHS - Block C                               20
G-14/4                                        20
F-10                                          20
I-8/3                                         20
Jinnah Gardens Phase 1                        20
G-11                                          19
Mumtaz City                                   19
DHA Defence Phase 5                           19
Bahria Enclave - Sector B1                    18
MPCHS - Block B                               18
D-12/1                                        17
Cube Apartments                               17
Bahria Enclave - Sector H                     16
G-13/2                                        16
F-11 Markaz                                   16
Oleander Sector - DHA Homes Block A           16
G-13/1                                        16
H-13                                          16
D-17                                          15
I-16/3                                        15
D-12/3                                        14
E-7                                           14
Soan Garden                                   14
Sukh Chayn Residence                          14
I-12/1                                        14
Askari Heights 4                              13
Bahria Enclave - Sector A                     13
Khanna Pul                                    13
D-12/2                                        12
I-8                                           12
Top City 1 - Block D                          12
Naval Anchorage                               11
DHA Phase 2 - Sector G                        11
Faisal Town Phase 1                           10
I-14                                          10
DHA Phase 2 - Sector D                        10
MPCHS - Block E                               10
I-10                                          10
G-11/3                                        10
Gulberg Heights                               10
DHA Phase 5 - Sector F                        10
G-9                                            9
F-17                                           9
G-9/3                                          9
E-11/4                                         9
Soan Garden - Block B                          9
DHA Defence Phase 1                            9
Gulberg Greens - Block A                       9
Bhara kahu                                     9
Faisal Town Phase 1 - Block A                  9
CBR Town Phase 1 - Block C                     8
Smama Star Mall & Residency                    8
I-11/2                                         8
I-8/4                                          8
Goldcrest Views                                8
DHA Phase 2 - Sector B                         8
DHA Phase 1 - Sector F                         8
I-8/2                                          8
Lilly Sector - Block A                         8
Askari Tower 4                                 8
MPCHS - Block C1                               8
Bahria Enclave - Sector G                      8
E-16/3                                         8
Karakoram Diplomatic Enclave                   7
Soan Garden - Block H                          7
G-9/4                                          7
DHA Valley - Oleander Sector                   7
F-10/3                                         7
PWD Housing Scheme                             7
G-10                                           7
Capital Residencia                             7
Faisal Town Phase 1 - Block C                  6
El Cielo                                       6
Defence Residency                              6
Lilly Sector - DHA Homes                       6
Park View City                                 6
Askari Tower 3                                 6
Diamond Mall & Residency                       6
MPCHS - Block B Extension 1                    6
G-9/1                                          6
Gulberg Residencia                             6
Silver Oaks Apartments                         6
F-10/1                                         6
Skypark One                                    6
Soan Garden - Block E                          6
Mumtaz City - Chanab Block                     6
DHA Phase 3 - Block B                          6
E-11/2                                         5
E-11/3                                         5
PHAF Officers Residencia                       5
DHA Phase 2 - Sector C                         5
Faisal Hills - Block A                         5
Margalla View Housing Society                  5
F-11/3                                         5
G-15                                           5
G-16/4                                         5
Gulberg Greens - Block C                       5
Emaar Canyon Views                             5
Oleander Sector - Block B                      5
F-11/4                                         5
E-11/1                                         5
F-6/2                                          5
Chak Shahzad                                   5
Bahria Enclave - Sector C3                     5
Bahria Enclave - Sector C2                     5
Askari Tower 1                                 5
Karakoram Greens                               5
F-8/3                                          4
Park View City - Downtown Block                4
MPCHS - Block A                                4
Soan Garden - Block D                          4
Gulberg Residencia - Block C                   4
I-14/4                                         4
Faisal Hills - Executive Block                 4
DHA Valley - Lilly Sector                      4
Warda Hamna Residencia 3                       4
Bahria Enclave - Sector I                      4
Defence Executive Apartments                   4
Korang Town                                    4
Zarkon Heights                                 4
The Royal Mall and Residency                   4
Zeta-1 Mall                                    4
Capital Square                                 4
DHA Phase 1 - Defence Villas                   4
G-10/2                                         4
DHA Phase 2 - Sector A                         4
MPCHS - Block D                                4
Bahria Enclave - Sector C                      4
F-6/1                                          4
Telegardens (T&T ECHS)                         4
Top City 1 - Block B                           4
Lignum Tower                                   4
DHA Phase 2 - Sector J                         4
Gulberg Arena Mall                             4
Naval Anchorage - Block G                      4
CBR Town Phase 1                               4
I-11                                           4
G-13/4                                         4
G-6                                            4
G-15/1                                         3
DHA Phase 1 - Sector E                         3
F-7/3                                          3
I-10/1                                         3
G-15/2                                         3
Bahria Garden City                             3
G-10/1                                         3
Constitution Avenue                            3
DHA Phase 5 - Sector B                         3
DHA Phase 1 - Sector B                         3
Gulberg Residencia - Block F                   3
Park Enclave 1                                 3
F-7/1                                          3
DHA Homes                                      3
G-13/3                                         3
Gulshan-e-Sehat 1                              3
Park View - Block H                            3
G-8                                            3
Goldcrest Highlife                             3
F-6/3                                          3
Robinas Luxury Residences                      3
F-10/4                                         3
Faisal Town Phase 1 - Block B                  3
Faisal Hills                                   3
Capital Homes                                  3
F-11/1                                         3
G-11/2                                         3
G-11 Markaz                                    3
G-10/4                                         3
Mumtaz City - Ravi Block                       3
Al-Ghurair Giga - Block 16                     3
New Blue Area                                  3
Gulberg Greens - Block E                       3
Gulberg Residencia - Block L                   3
The Galleria                                   3
F-10 Markaz                                    3
Lilly Sector - Block B                         3
Kazani Heights                                 3
I-16                                           3
Al-Safa Heights                                3
Gulberg Greens - Block B                       3
Bahria Enclave - Sector J                      3
Shah Allah Ditta                               3
Bahria Garden City - Zone 1                    3
Oleander Sector - DHA Homes                    3
DHA Phase 2 - Sector E                         3
DHA Defence Phase 3                            3
PWD Housing Society - Block A                  3
G-8/2                                          2
F-8/4                                          2
Capital Heights                                2
Ghauri Town                                    2
Zaraj Scheme - Sector C                        2
Al-Ghurair Giga - Block 15                     2
Jhangi Syedan                                  2
Gulberg Residencia - Block I                   2
F-8/1                                          2
The Arch                                       2
Executive Heights                              2
National Police Foundation O-9 - Block C       2
Airport Green Garden - Block A                 2
G-11/1                                         2
Elysium Mall                                   2
Tarnol                                         2
Chak Shahzad Farms                             2
F-7/2                                          2
Burma Town                                     2
Arsalan Town                                   2
G-6/3                                          2
River Garden                                   2
I-14/1                                         2
Gulberg Residencia - Block J                   2
PWD Housing Society - Block D                  2
DHA Phase 3 - Block A                          2
E-16/2                                         2
Islamabad Expressway                           2
Lehtrar Road                                   2
Grand Orchard                                  2
National Police Foundation O-9                 2
Al-Ghurair Giga - Block 7                      2
Al-Ghurair Giga                                2
Gulberg Greens - Executive Block               2
I-8/1                                          2
Airport Enclave                                2
F-17/2                                         2
Margalla View Society - Block C                2
Gulshan-e-Sehat 1 - Hamza Block                2
DHA Phase 2 - Sector F                         2
CBR Town Phase 1 - Block D                     1
Margalla View Society - Block D                1
Ghauri Town - VIP Block                        1
Margalla Town Phase 1                          1
Fazaia Housing Scheme Block B                  1
DHA Phase 5 - Sector J                         1
DHA Phase 4 - Overseas Sector                  1
Park View - Block B                            1
Gulberg Residencia - Block A                   1
DHA Phase 1 - Sector A                         1
Kuri Road                                      1
Pine Heights Luxury Apartments                 1
G-10 Markaz                                    1
Sehala Farm House                              1
Mall of Islamabad                              1
Al Qaim Town                                   1
PAF Tarnol - Block D                           1
Gulshan-e-Sehat 2 - Block G                    1
Rawalpindi Housing Society                     1
Pine City Housing Society                      1
Taramrri                                       1
Pakistan Town - Phase 2                        1
Pakistan Town - Phase 1                        1
Shehzad Town                                   1
G-12                                           1
Zara Heights                                   1
Naval Anchorage - Block J                      1
Green Avenue                                   1
Al-Ghurair Giga - Block 12                     1
DHA Phase 5 - Sector A                         1
I-11/1                                         1
The Atrium                                     1
Pir Sohawa Road                                1
Al-Ghurair Giga - Block 5                      1
Al-Ghurair Giga - Block 8                      1
Rawal Enclave                                  1
Karakoram Enclave 2                            1
18 West Residencia                             1
Blue Area                                      1
G-11/4                                         1
Park Enclave                                   1
I-12                                           1
Top City 1 - Block K                           1
Capital Resorts                                1
Top City 1 - Kanwar Moiz Block                 1
Bahria Enclave - Sector F1                     1
Gulberg Residencia - Block Q                   1
Multi Residencia & Orchards                    1
G-15 Markaz                                    1
PWD Housing Society - Block B                  1
DHA Phase 2 - Sector H                         1
Kashmir Highway                                1
Gulberg Residencia - D Markaz                  1
Park Avenue                                    1
University Town                                1
F-7/4                                          1
DHA Phase 6 - Sector A                         1
Bahria Garden City West                        1
G-8/1                                          1
E-17/3                                         1
Islamabad - Murree Expressway                  1
I-10/2                                         1
F-11/2                                         1
I-10/4                                         1
Tarlai                                         1
Gulberg Residencia - Block O                   1
Kazani Resorts                                 1
Naval Anchorage - Block D                      1
Soan Garden - Block A                          1
G-15/4                                         1
Oleander Sector - DHA Homes Block B            1
DHA Valley                                     1
Gulberg Business Square                        1
Minara Residence                               1
The Veranda Residence                          1
Gulberg Residencia - Block D                   1
Top City 1 - Block C                           1
Elanza Mall & Residency                        1
British Homes Phase 2                          1
Naval Anchorage - Block K                      1
Aries Tower                                    1
Meher Apartments                               1
Madina Tower                                   1
G-8 Markaz                                     1
G-7/4                                          1
Faisal Hills - Block C                         1
Ghauri Town Phase 5B                           1
I-16/2                                         1
Gevora International Hotel & Mall              1
I-14/3                                         1
Marwa Town                                     1
Askari Tower 2                                 1
Bahria Garden City - Zone 5                    1
FOECHS - Foreign Office Employees Society      1
DHA Phase 4 - Sector A                         1
D-12 Markaz                                    1
G-16/3                                         1
G-14                                           1
Ghauri Town Phase 4B                           1
Soan Garden - Block C                          1
PECHS - Block K                                1
CBR Town Phase 1 - Block B                     1
PECHS - Block K Extension                      1
Bahria Garden City - Zone 4                    1
Landmark Heights                               1
G-14/3                                         1
E-18                                           1
AJ Towers                                      1
Mall of Imarat                                 1
Phulgran                                       1
Aryan Enclave                                  1
One Constitution Avenue                        1
Bahria Enclave - Sector F                      1
Soan Garden - Block H Extension                1
Name: count, dtype: int64

In [24]:
with pd.option_context('display.max_rows', None):
    print(df['Real Location'].value_counts())

Real Location
DHA Defence Phase 2, DHA Defence                                            172
Bani Gala, Islamabad                                                         90
G-13, Islamabad                                                              84
D-12, Islamabad                                                              74
B-17, Islamabad                                                              67
Bahria Enclave, Bahria Town                                                  61
Top City 1, Islamabad                                                        54
F-8, Islamabad                                                               47
MPCHS - Block F, MPCHS - Multi Gardens                                       44
F-7, Islamabad                                                               44
Bahria Enclave - Sector C1, Bahria Enclave                                   42
Bahria Enclave - Sector N, Bahria Enclave                                    41
MPCHS - Multi Gardens, B-17                                                  40
F-6, Islamabad                                                               39
Gulberg Greens, Gulberg                                                      34
The Centaurus, F-8                                                           31
F-11, Islamabad                                                              29
Jinnah Gardens, FECHS                                                        26
Faisal Margalla City, B-17                                                   26
Eighteen, Kashmir Highway                                                    25
Top City 1 - Block A, Top City 1                                             24
D-12/4, D-12                                                                 23
E-11, Islamabad                                                              23
Diplomatic Enclave, Islamabad                                                21
Faisal Town - F-18, Islamabad                                                21
MPCHS - Block C, MPCHS - Multi Gardens                                       20
G-14/4, G-14                                                                 20
F-10, Islamabad                                                              20
I-8/3, I-8                                                                   20
Jinnah Gardens Phase 1, Jinnah Gardens                                       20
G-11, Islamabad                                                              19
Mumtaz City, Islamabad                                                       19
DHA Defence Phase 5, DHA Defence                                             19
Bahria Enclave - Sector B1, Bahria Enclave                                   18
MPCHS - Block B, MPCHS - Multi Gardens                                       18
D-12/1, D-12                                                                 17
Cube Apartments, Bahria Enclave                                              17
Bahria Enclave - Sector H, Bahria Enclave                                    16
G-13/2, G-13                                                                 16
F-11 Markaz, F-11                                                            16
Oleander Sector - DHA Homes Block A, DHA Valley - Oleander Sector            16
G-13/1, G-13                                                                 16
H-13, Islamabad                                                              16
D-17, Islamabad                                                              15
I-16/3, I-16                                                                 15
D-12/3, D-12                                                                 14
E-7, Islamabad                                                               14
Soan Garden, Islamabad                                                       14
Sukh Chayn Residence, F-10                                                   14
I-12/1, I-12                                                                 14
Askari Heights 4, DHA Phase 5 - Sector H                                     13
Bahria Enclave - Sector A, Bahria Enclave                                    13
Khanna Pul, Islamabad                                                        13
D-12/2, D-12                                                                 12
I-8, Islamabad                                                               12
Top City 1 - Block D, Top City 1                                             12
Naval Anchorage, Islamabad                                                   11
DHA Phase 2 - Sector G, DHA Defence Phase 2                                  11
Faisal Town Phase 1, Faisal Town - F-18                                      10
I-14, Islamabad                                                              10
DHA Phase 2 - Sector D, DHA Defence Phase 2                                  10
MPCHS - Block E, MPCHS - Multi Gardens                                       10
I-10, Islamabad                                                              10
G-11/3, G-11                                                                 10
Gulberg Heights, Gulberg Greens                                              10
DHA Phase 5 - Sector F, DHA Defence Phase 5                                  10
G-9, Islamabad                                                                9
F-17, Islamabad                                                               9
G-9/3, G-9                                                                    9
E-11/4, E-11                                                                  9
Soan Garden - Block B, Soan Garden                                            9
DHA Defence Phase 1, DHA Defence                                              9
Gulberg Greens - Block A, Gulberg Greens                                      9
Bhara kahu, Islamabad                                                         9
Faisal Town Phase 1 - Block A, Faisal Town Phase 1                            9
CBR Town Phase 1 - Block C, CBR Town Phase 1                                  8
Smama Star Mall & Residency, Gulberg Greens                                   8
I-11/2, I-11                                                                  8
I-8/4, I-8                                                                    8
Goldcrest Views, DHA Defence Phase 2                                          8
DHA Phase 2 - Sector B, DHA Defence Phase 2                                   8
DHA Phase 1 - Sector F, DHA Defence Phase 1                                   8
I-8/2, I-8                                                                    8
Lilly Sector - Block A, DHA Valley - Lilly Sector                             8
Askari Tower 4, DHA Defence Phase 5                                           8
MPCHS - Block C1, MPCHS - Multi Gardens                                       8
Bahria Enclave - Sector G, Bahria Enclave                                     8
E-16/3, E-16                                                                  8
Karakoram Diplomatic Enclave, Islamabad                                       7
Soan Garden - Block H, Soan Garden                                            7
G-9/4, G-9                                                                    7
DHA Valley - Oleander Sector, DHA Valley                                      7
F-10/3, F-10                                                                  7
PWD Housing Scheme, Islamabad                                                 7
G-10, Islamabad                                                               7
Capital Residencia, Margalla Hills-2                                          7
Faisal Town Phase 1 - Block C, Faisal Town Phase 1                            6
El Cielo, GT Road                                                             6
Defence Residency, DHA Defence Phase 2                                        6
Lilly Sector - DHA Homes, DHA Valley - Lilly Sector                           6
Park View City, Islamabad                                                     6
Askari Tower 3, DHA Defence Phase 5                                           6
Diamond Mall & Residency, Gulberg Greens                                      6
MPCHS - Block B Extension 1, MPCHS - Multi Gardens                            6
G-9/1, G-9                                                                    6
Gulberg Residencia, Gulberg                                                   6
Silver Oaks Apartments, F-10                                                  6
F-10/1, F-10                                                                  6
Skypark One, Gulberg Greens                                                   6
Soan Garden - Block E, Soan Garden                                            6
Mumtaz City - Chanab Block, Mumtaz City                                       6
DHA Phase 3 - Block B, DHA Defence Phase 3                                    6
E-11/2, E-11                                                                  5
E-11/3, E-11                                                                  5
PHAF Officers Residencia, Kuri Road                                           5
DHA Phase 2 - Sector C, DHA Defence Phase 2                                   5
Faisal Hills - Block A, Faisal Hills                                          5
Margalla View Housing Society, D-17                                           5
F-11/3, F-11                                                                  5
G-15, Islamabad                                                               5
G-16/4, G-16                                                                  5
Gulberg Greens - Block C, Gulberg Greens                                      5
Emaar Canyon Views, Islamabad                                                 5
Oleander Sector - Block B, DHA Valley - Oleander Sector                       5
F-11/4, F-11                                                                  5
E-11/1, E-11                                                                  5
F-6/2, F-6                                                                    5
Chak Shahzad, Islamabad                                                       5
Bahria Enclave - Sector C3, Bahria Enclave                                    5
Bahria Enclave - Sector C2, Bahria Enclave                                    5
Askari Tower 1, DHA Defence Phase 2                                           5
Karakoram Greens, Gulberg Greens                                              5
F-8/3, F-8                                                                    4
Park View City - Downtown Block, Park View City                               4
MPCHS - Block A, MPCHS - Multi Gardens                                        4
Soan Garden - Block D, Soan Garden                                            4
Gulberg Residencia - Block C, Gulberg Residencia                              4
I-14/4, I-14                                                                  4
Faisal Hills - Executive Block, Faisal Hills                                  4
DHA Valley - Lilly Sector, DHA Valley                                         4
Warda Hamna Residencia 3, G-11/3                                              4
Bahria Enclave - Sector I, Bahria Enclave                                     4
Defence Executive Apartments, DHA Defence Phase 2                             4
Korang Town, Islamabad                                                        4
Zarkon Heights, G-15                                                          4
The Royal Mall and Residency, Bahria Enclave                                  4
Zeta-1 Mall, GT Road                                                          4
Capital Square, B-17                                                          4
DHA Phase 1 - Defence Villas, DHA Phase 1 - Sector F                          4
G-10/2, G-10                                                                  4
DHA Phase 2 - Sector A, DHA Defence Phase 2                                   4
MPCHS - Block D, MPCHS - Multi Gardens                                        4
Bahria Enclave - Sector C, Bahria Enclave                                     4
F-6/1, F-6                                                                    4
Telegardens (T&T ECHS), F-17                                                  4
Top City 1 - Block B, Top City 1                                              4
Lignum Tower, DHA Defence Phase 2                                             4
DHA Phase 2 - Sector J, DHA Defence Phase 2                                   4
Gulberg Arena Mall, Gulberg Greens                                            4
Naval Anchorage - Block G, Naval Anchorage                                    4
CBR Town Phase 1, CBR Town                                                    4
I-11, Islamabad                                                               4
G-13/4, G-13                                                                  4
G-6, Islamabad                                                                4
G-15/1, G-15                                                                  3
DHA Phase 1 - Sector E, DHA Defence Phase 1                                   3
F-7/3, F-7                                                                    3
I-10/1, I-10                                                                  3
G-15/2, G-15                                                                  3
Bahria Garden City, Bahria Town                                               3
G-10/1, G-10                                                                  3
Constitution Avenue, Islamabad                                                3
DHA Phase 5 - Sector B, DHA Defence Phase 5                                   3
DHA Phase 1 - Sector B, DHA Defence Phase 1                                   3
Gulberg Residencia - Block F, Gulberg Residencia                              3
Park Enclave 1, Park Enclave                                                  3
F-7/1, F-7                                                                    3
DHA Homes, DHA Valley                                                         3
G-13/3, G-13                                                                  3
Gulshan-e-Sehat 1, E-18                                                       3
Park View - Block H, Park View City                                           3
G-8, Islamabad                                                                3
Goldcrest Highlife, DHA Defence Phase 2                                       3
F-6/3, F-6                                                                    3
Robinas Luxury Residences, Bani Gala                                          3
F-10/4, F-10                                                                  3
Faisal Town Phase 1 - Block B, Faisal Town Phase 1                            3
Faisal Hills, Islamabad                                                       3
Capital Homes, H-13                                                           3
F-11/1, F-11                                                                  3
G-11/2, G-11                                                                  3
G-11 Markaz, G-11                                                             3
G-10/4, G-10                                                                  3
Mumtaz City - Ravi Block, Mumtaz City                                         3
Al-Ghurair Giga - Block 16, Al-Ghurair Giga                                   3
New Blue Area, Islamabad                                                      3
Gulberg Greens - Block E, Gulberg Greens                                      3
Gulberg Residencia - Block L, Gulberg Residencia                              3
The Galleria, Bahria Enclave                                                  3
F-10 Markaz, F-10                                                             3
Lilly Sector - Block B, DHA Valley - Lilly Sector                             3
Kazani Heights, Islamabad Expressway                                          3
I-16, Islamabad                                                               3
Al-Safa Heights, F-11 Markaz                                                  3
Gulberg Greens - Block B, Gulberg Greens                                      3
Bahria Enclave - Sector J, Bahria Enclave                                     3
Shah Allah Ditta, Islamabad                                                   3
Bahria Garden City - Zone 1, Bahria Garden City                               3
Oleander Sector - DHA Homes, DHA Valley - Oleander Sector                     3
DHA Phase 2 - Sector E, DHA Defence Phase 2                                   3
DHA Defence Phase 3, DHA Defence                                              3
PWD Housing Society - Block A, PWD Housing Scheme                             3
G-8/2, G-8                                                                    2
F-8/4, F-8                                                                    2
Capital Heights, G-11/3                                                       2
Ghauri Town, Islamabad                                                        2
Zaraj Scheme - Sector C, Zaraj Housing Scheme                                 2
Al-Ghurair Giga - Block 15, Al-Ghurair Giga                                   2
Jhangi Syedan, Islamabad                                                      2
Gulberg Residencia - Block I, Gulberg Residencia                              2
F-8/1, F-8                                                                    2
The Arch, G-11/3                                                              2
Executive Heights, F-11                                                       2
National Police Foundation O-9 - Block C, National Police Foundation O-9      2
Airport Green Garden - Block A, Airport Green Garden                          2
G-11/1, G-11                                                                  2
Elysium Mall, Blue Area                                                       2
Tarnol, Islamabad                                                             2
Chak Shahzad Farms, Chak Shahzad                                              2
F-7/2, F-7                                                                    2
Burma Town, Islamabad                                                         2
Arsalan Town, Islamabad                                                       2
G-6/3, G-6                                                                    2
River Garden, Islamabad                                                       2
I-14/1, I-14                                                                  2
Gulberg Residencia - Block J, Gulberg Residencia                              2
PWD Housing Society - Block D, PWD Housing Scheme                             2
DHA Phase 3 - Block A, DHA Defence Phase 3                                    2
E-16/2, E-16                                                                  2
Islamabad Expressway, Islamabad                                               2
Lehtrar Road, Islamabad                                                       2
Grand Orchard, DHA Defence Phase 1                                            2
National Police Foundation O-9, Islamabad                                     2
Al-Ghurair Giga - Block 7, Al-Ghurair Giga                                    2
Al-Ghurair Giga, DHA Defence Phase 2                                          2
Gulberg Greens - Executive Block, Gulberg Greens                              2
I-8/1, I-8                                                                    2
Airport Enclave, Islamabad                                                    2
F-17/2, F-17                                                                  2

In [22]:
# Assuming your dataframe is named housing_data
df['Real Location'].str.split(',').str.get(1).str.split(' - ', n=1, expand=True)

                    0     1
0                D-12  None
1                D-12  None
2                D-12  None
3                D-12  None
4      Bahria Enclave  None
...               ...   ...
2682        Islamabad  None
2683        Islamabad  None
2684        Islamabad  None
2685        Islamabad  None
2686       Top City 1  None

[2685 rows x 2 columns]

### Price
Selecting a common unit

In [25]:
df['Price'].str.split(' ').str.get(1).value_counts()

Price
Crore    2428
Lakh      236
Arab       21
Name: count, dtype: int64

In [26]:
df['Price'].str.split(' ').str.get(0).str[3:].astype('float')

0       12.00
1        5.20
2        4.30
3        5.75
4        2.70
        ...
2682    55.00
2683    25.00
2684    22.00
2685    30.00
2686     5.50
Name: Price, Length: 2685, dtype: float64

In [27]:
def Price_to_Cr(series):
    unit = series.strip().split(' ')[1]
    price = float(series.strip().split(' ')[0][3:])
    if (unit =='Lakh'):
        price = price / 100
    elif (unit =='Arab'):
        price = price * 100

    series = price
    return series

In [28]:
df['Price'].apply(Price_to_Cr)

0       12.00
1        5.20
2        4.30
3        5.75
4        2.70
        ...
2682    55.00
2683    25.00
2684    22.00
2685    30.00
2686     5.50
Name: Price, Length: 2685, dtype: float64

In [29]:
df['Price'] = df['Price'].apply(Price_to_Cr)

In [30]:
df['Price'].sample(10)

21       2.90
2497     3.50
442      3.90
1677     2.50
1887     4.00
1968     9.75
500      0.44
2578    11.75
698      6.30
2640     1.25
Name: Price, dtype: float64

In [31]:
df.rename(columns={"Price":'Price(Cr)'},inplace=True)

### Bath(s)
There is '-' category,<br>We can fill it from 'Amenities: Room'

In [32]:
df['Bath(s)'].value_counts()

Bath(s)
6     886
5     389
4     308
2     296
3     261
7     204
1     181
-     157
10      2
9       1
Name: count, dtype: int64

In [33]:
df[df['Bath(s)'] == '-']['Amenities: Rooms'].str.split(',').str.get(1).str.split(':').str.get(0).value_counts()

Amenities: Rooms
Bathrooms                 100
Dining Room                19
Lounge or Sitting Room      1
Drawing Room                1
Other Rooms                 1
Servant Quarters            1
Name: count, dtype: int64

In [34]:
df[df['Bath(s)'] == '-']['Amenities: Rooms'].sample(5)

2670                                                  NaN
116                                                   NaN
2580    Bedrooms: 6, Bathrooms: 2, Servant Quarters: 2...
1492                                                  NaN
1724    Bedrooms: 2, Bathrooms: 2, Servant Quarters: 1...
Name: Amenities: Rooms, dtype: str

<br>

**Will remove those rows where you cannot fill the 'Bath(s)' information from 'Amenities: Room'**

In [35]:
temp = df[df['Bath(s)'] == '-']['Amenities: Rooms'].str.split('Bathrooms').str.get(1).str.split(',').str.get(0).str.strip()
empty_idxs = temp[temp==''].index

In [39]:
temp.sample(5)

1053    : 9
519     : 7
1790    : 4
955     NaN
659     NaN
Name: Amenities: Rooms, dtype: object

In [41]:
empty_idxs

Index([129, 1059, 1587], dtype='int64')

In [42]:
df.drop(index=empty_idxs,inplace=True)

In [43]:
df.shape[0]

2682

### Area
Converting Kanal to Marla. <br>
1 Kanal = 20 Marla

In [44]:
df['Area'].sample(5)

1151    17.8 Marla
2227       7 Marla
168      1.8 Kanal
256       10 Marla
1636       1 Kanal
Name: Area, dtype: str

In [45]:
# No other unit for Area
df['Area'].str.split().str.get(1).value_counts()

Area
Marla    2021
Kanal     661
Name: count, dtype: int64

In [46]:
def Areaunitconverter(series):
    unit = series.split()[1].strip()
    no = float(series.split()[0])
    if unit == 'Kanal':
        no *= 20

    return no

In [47]:
df['Area'].apply(Areaunitconverter).tail(5)

2682    42.0
2683    20.0
2684    17.8
2685    26.0
2686    10.0
Name: Area, dtype: float64

In [48]:
df['Area'].tail(5)

2682     2.1 Kanal
2683       1 Kanal
2684    17.8 Marla
2685     1.3 Kanal
2686      10 Marla
Name: Area, dtype: str

In [49]:
df['Area'] = df['Area'].apply(Areaunitconverter)

In [50]:
df.rename(columns={'Area':'Area(Marla)'},inplace=True)

### Location
Remove the part 'Islamabad, Islmabad Capital' since it is the same every where.

In [51]:
df['Location']

0              D-12, Islamabad, Islamabad Capital
1              D-12, Islamabad, Islamabad Capital
2              D-12, Islamabad, Islamabad Capital
3              D-12, Islamabad, Islamabad Capital
4       Bahria Town, Islamabad, Islamabad Capital
                          ...
2682            F-8, Islamabad, Islamabad Capital
2683            F-8, Islamabad, Islamabad Capital
2684            F-8, Islamabad, Islamabad Capital
2685            F-7, Islamabad, Islamabad Capital
2686     Top City 1, Islamabad, Islamabad Capital
Name: Location, Length: 2682, dtype: str

In [52]:
df['Location'].str.split(',',n=1).str.get(1).value_counts()

Location
Islamabad, Islamabad Capital    2682
Name: count, dtype: int64

In [53]:
pd.set_option('display.max_rows', None)

In [54]:
df['Location'].str.split(',').str.get(0).value_counts().sort_index()

Location
Airport Enclave                                2
Al Qaim Town                                   1
Arsalan Town                                   2
B-17                                         250
Bahria Town                                  255
Bani Gala                                     94
Bhara kahu                                     9
Blue Area                                      4
Burma Town                                     2
C-18                                           1
CBR Town                                      14
Chak Shahzad                                   7
Constitution Avenue                            4
D-12                                         141
D-17                                          24
DHA Defence                                  424
Diplomatic Enclave                            21
E-11                                          57
E-16                                          10
E-17                                           1
E-18                                           7
E-7                                           14
Emaar Canyon Views                             5
F-10                                          59
F-11                                          67
F-17                                          15
F-6                                           51
F-7                                           53
F-8                                           86
FECHS                                         47
FOECHS - Foreign Office Employees Society      1
Faisal Hills                                  13
Faisal Town - F-18                            49
G-10                                          18
G-11                                          45
G-12                                           1
G-13                                         123
G-14                                          22
G-15                                          17
G-16                                           6
G-6                                            6
G-7                                            1
G-8                                            7
G-9                                           31
GT Road                                       11
Ghauri Town                                    6
Green Avenue                                   1
Gulberg                                      125
H-12                                           1
H-13                                          20
I-10                                          15
I-11                                          13
I-12                                          15
I-13                                           1
I-14                                          17
I-16                                          19
I-8                                           50
Islamabad - Murree Expressway                  1
Islamabad Expressway                           5
Jhangi Syedan                                  2
Karakoram Diplomatic Enclave                   7
Kashmir Highway                               28
Khanna Pul                                    13
Korang Town                                    4
Kuri Road                                      6
Lehtrar Road                                   2
Margalla Town                                  1
Marwa Town                                     1
Multi Residencia & Orchards                    1
Mumtaz City                                   28
National Police Foundation O-9                 4
Naval Anchorage                               18
New Blue Area                                  3
PAF Tarnol                                     1
PECHS                                          2
PWD Housing Scheme                            13
Pakistan Town                                  2
Park Enclave                                   4
Park View City                                14
Phulgran                                       1
Pir Sohawa                                     2
Rawal Enclave                                  1
River Garden                                   2
Sehala Farm House                              1
Shah Allah Ditta                               3
Shehzad Town                                   1
Simly Dam Road                                 1
Soan Garden                                   43
Taramrri                                       1
Tarlai                                         1
Tarnol                                         3
Top City 1                                    97
University Town                                1
Zaraj Housing Scheme                           3
Name: count, dtype: int64

In [55]:
df['Location'] = df['Location'].str.split(',').str.get(0).str.strip()

In [56]:
df.info()

<class 'pandas.DataFrame'>
Index: 2682 entries, 0 to 2686
Data columns (total 15 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Real Location                                     2682 non-null   str
 1   Type                                              2682 non-null   str
 2   Price(Cr)                                         2682 non-null   float64
 3   Bath(s)                                           2682 non-null   str
 4   Area(Marla)                                       2682 non-null   float64
 5   Bedroom(s)                                        2682 non-null   str
 6   Location                                          2682 non-null   object
 7   Description                                       2682 non-null   str
 8   Amenities: Main Features                          2551 non-null   str
 9   Amenities: Rooms                                  2475 non-null   str
 10  Amenities: Business and Communication             2425 non-null   str
 11  Amenities: Community Features                     2409 non-null   str
 12  Amenities: Healthcare Recreational                2178 non-null   str
 13  Amenities: Nearby Locations and Other Facilities  2569 non-null   str
 14  Amenities: Other Facilities                       2392 non-null   str
dtypes: float64(2), object(1), str(12)
memory usage: 4.1+ MB

In [57]:
df['Amenities: Rooms'].iloc[0]

'Bedrooms: 6, Bathrooms: 8, Servant Quarters: 2, Drawing Room, Dining Room, Kitchens: 2, Study Room, Prayer Room, Powder Room, Gym, Store Rooms: 1, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms'

In [58]:
df['Amenities: Main Features'].iloc[1]

'Built in year, Parking Spaces: 3, Double Glazed Windows, Central Air Conditioning, Central Heating, Flooring, Electricity Backup, Waste Disposal, Floors: 2, Other Main Features'

In [59]:
df.to_csv('zameen_new_cleaned_v1.csv')