In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('zameen_new.csv',index_col=0)

In [3]:
df.head()

,Scraped_URL,Real Location,Type,Price,Bath(s),Area,Purpose,Bedroom(s),Added,Location,...,Amenities: Community Features,Amenities: Healthcare Recreational,Amenities: Nearby Locations and Other Facilities,Amenities: Other Facilities,Initial Amount,Monthly Installment,Remaining Installments,Balloon Payments,Total Balloon Payment,Possession Fee
0,https://www.zameen.com/Property/d_12_d-12_2_10...,"D-12/2, D-12",House,PKR12 Crore,7,10 Marla,For Sale,6,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.zameen.com/Property/d_12_d-12_1_4_...,"D-12/1, D-12",House,PKR5.2 Crore,4,4.4 Marla,For Sale,3,2 months ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Security Staff, Other Facilities",NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.zameen.com/Property/d_12_d-12_4_4_...,"D-12/4, D-12",House,PKR4.3 Crore,5,4.4 Marla,For Sale,3,1 month ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.zameen.com/Property/d_12_d-12_1_5_...,"D-12/1, D-12",House,PKR5.75 Crore,6,5 Marla,For Sale,5,3 weeks ago,"D-12, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.zameen.com/Property/bahria_enclave...,"Bahria Enclave - Sector H, Bahria Enclave",House,PKR2.7 Crore,4,5 Marla,For Sale,3,4 months ago,"Bahria Town, Islamabad, Islamabad Capital",...,"Community Lawn or Garden, Community Swimming P...","Lawn or Garden, Swimming Pool, Sauna, Jacuzzi,...","Nearby Schools, Nearby Hospitals, Nearby Shopp...","Maintenance Staff, Security Staff, Facilities ...",NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
Index: 6463 entries, 0 to 6482
Data columns (total 24 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Scraped_URL                                       6463 non-null   str
 1   Real Location                                     6463 non-null   str
 2   Type                                              6463 non-null   str
 3   Price                                             6463 non-null   str
 4   Bath(s)                                           6463 non-null   str
 5   Area                                              6463 non-null   str
 6   Purpose                                           6463 non-null   str
 7   Bedroom(s)                                        6463 non-null   str
 8   Added                                             6463 non-null   str
 9   Location                                          6463 non-null   str
 10  Description                                       6463 non-null   str
 11  Amenities: Main Features                          6003 non-null   str
 12  Amenities: Rooms                                  5840 non-null   str
 13  Amenities: Business and Communication             5649 non-null   str
 14  Amenities: Community Features                     5605 non-null   str
 15  Amenities: Healthcare Recreational                5051 non-null   str
 16  Amenities: Nearby Locations and Other Facilities  6033 non-null   str
 17  Amenities: Other Facilities                       5646 non-null   str
 18  Initial Amount                                    170 non-null    str
 19  Monthly Installment                               170 non-null    str
 20  Remaining Installments                            170 non-null    str
 21  Balloon Payments                                  1 non-null      str
 22  Total Balloon Payment                             1 non-null      str
 23  Possession Fee                                    1 non-null      str
dtypes: str(24)
memory usage: 11.2 MB

In [5]:
df.isnull().sum()

Scraped_URL                                            0
Real Location                                          0
Type                                                   0
Price                                                  0
Bath(s)                                                0
Area                                                   0
Purpose                                                0
Bedroom(s)                                             0
Added                                                  0
Location                                               0
Description                                            0
Amenities: Main Features                             460
Amenities: Rooms                                     623
Amenities: Business and Communication                814
Amenities: Community Features                        858
Amenities: Healthcare Recreational                  1412
Amenities: Nearby Locations and Other Facilities     430
Amenities: Other Facilities                          817
Initial Amount                                      6293
Monthly Installment                                 6293
Remaining Installments                              6293
Balloon Payments                                    6462
Total Balloon Payment                               6462
Possession Fee                                      6462
dtype: int64

In [8]:
df.columns

Index(['Scraped_URL', 'Real Location', 'Type', 'Price', 'Bath(s)', 'Area',
       'Purpose', 'Bedroom(s)', 'Added', 'Location', 'Description',
       'Amenities: Main Features', 'Amenities: Rooms',
       'Amenities: Business and Communication',
       'Amenities: Community Features', 'Amenities: Healthcare Recreational',
       'Amenities: Nearby Locations and Other Facilities',
       'Amenities: Other Facilities', 'Initial Amount', 'Monthly Installment',
       'Remaining Installments', 'Balloon Payments', 'Total Balloon Payment',
       'Possession Fee'],
      dtype='str')

In [6]:
df.duplicated().sum()

np.int64(0)

In [9]:
cols_to_remove = ['Scraped_URL','Purpose','Added','Initial Amount','Monthly Installment','Remaining Installments',
                  'Balloon Payments', 'Total Balloon Payment','Possession Fee']

In [10]:
df.drop(columns=cols_to_remove,inplace=True)

In [11]:
df.info()

<class 'pandas.DataFrame'>
Index: 6463 entries, 0 to 6482
Data columns (total 15 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Real Location                                     6463 non-null   str
 1   Type                                              6463 non-null   str
 2   Price                                             6463 non-null   str
 3   Bath(s)                                           6463 non-null   str
 4   Area                                              6463 non-null   str
 5   Bedroom(s)                                        6463 non-null   str
 6   Location                                          6463 non-null   str
 7   Description                                       6463 non-null   str
 8   Amenities: Main Features                          6003 non-null   str
 9   Amenities: Rooms                                  5840 non-null   str
 10  Amenities: Business and Communication             5649 non-null   str
 11  Amenities: Community Features                     5605 non-null   str
 12  Amenities: Healthcare Recreational                5051 non-null   str
 13  Amenities: Nearby Locations and Other Facilities  6033 non-null   str
 14  Amenities: Other Facilities                       5646 non-null   str
dtypes: str(15)
memory usage: 9.8 MB

In [12]:
df.duplicated().sum()

np.int64(97)

In [13]:
df['Real Location'].sample(10)

4217                                   G-14/4, G-14
2217          DHA Valley - Lilly Sector, DHA Valley
5144                                     F-6/4, F-6
6247                      Orchard Scheme, Islamabad
3712    DHA Phase 5 - Sector B, DHA Defence Phase 5
2030                Gulberg Heights, Gulberg Greens
2722                          Jinnah Gardens, FECHS
1245                    Bahria Enclave, Bahria Town
4360               DHA Defence Phase 3, DHA Defence
178                DHA Defence Phase 2, DHA Defence
Name: Real Location, dtype: str

In [14]:
with pd.option_context('display.max_rows', None):
    print(df['Real Location'].str.split(',').str.get(0).value_counts())

Real Location
DHA Defence Phase 2                                                363
Bani Gala                                                          242
G-13                                                               213
D-12                                                               133
Top City 1                                                         125
B-17                                                               123
F-8                                                                116
Bahria Enclave                                                     103
F-7                                                                 91
MPCHS - Block F                                                     81
Faisal Town - F-18                                                  81
MPCHS - Multi Gardens                                               80
F-6                                                                 74
G-11                                                                71
E-11                                                                70
F-11                                                                68
Gulberg Greens                                                      65
Faisal Margalla City                                                65
Jinnah Gardens                                                      64
Bahria Enclave - Sector N                                           62
Bahria Enclave - Sector C1                                          57
The Centaurus                                                       54
Jinnah Gardens Phase 1                                              54
Eighteen                                                            52
Soan Garden                                                         51
F-10                                                                49
DHA Defence Phase 5                                                 49
D-17                                                                48
G-13/1                                                              44
H-13                                                                44
Top City 1 - Block A                                                44
I-12/1                                                              44
MPCHS - Block C                                                     41
Sukh Chayn Residence                                                40
Defence Residency                                                   39
Mumtaz City                                                         38
MPCHS - Block B                                                     38
Faisal Town Phase 1 - Block A                                       38
E-7                                                                 37
G-13/2                                                              37
MPCHS - Block E                                                     36
G-14/4                                                              35
G-11/3                                                              35
D-12/4                                                              34
Diplomatic Enclave                                                  34
I-8/3                                                               33
I-16/3                                                              33
Askari Heights 4                                                    32
D-12/1                                                              30
G-9                                                                 30
Bahria Enclave - Sector H                                           29
F-17                                                                28
F-11 Markaz                                                         28
Bahria Enclave - Sector B1                                          28
Cube Apartments                                                     27
Oleander Sector - DHA Homes Block A                                 27
PHAF Officers Residencia                                            27
Bahria Enclave - Sector A                                           27
Zarkon Heights                                                      26
Naval Anchorage                                                     25
I-8                                                                 25
G-15                                                                25
I-14                                                                24
G-9/3                                                               24
DHA Phase 2 - Sector B                                              24
Faisal Town Phase 1 - Block C                                       23
G-10                                                                23
Soan Garden - Block H                                               22
E-11/4                                                              22
Top City 1 - Block D                                                22
Faisal Town Phase 1                                                 21
G-9/4                                                               21
Goldcrest Views                                                     21
G-9/1                                                               21
G-13/3                                                              21
Capital Residencia                                                  21
Smama Star Mall & Residency                                         20
PWD Housing Scheme                                                  20
DHA Defence Phase 1                                                 20
Bhara kahu                                                          20
DHA Phase 5 - Sector F                                              20
F-8/3                                                               19
MPCHS - Block C1                                                    19
D-12/2                                                              18
I-8/2                                                               18
DHA Phase 2 - Sector G                                              18
F-11/3                                                              18
I-10                                                                18
Skypark One                                                         18
Gulberg Heights                                                     18
G-13/4                                                              18
D-12/3                                                              17
CBR Town Phase 1 - Block C                                          17
Gulberg Greens - Block C                                            17
Goldcrest Highlife                                                  17
Askari Tower 1                                                      17
F-7/1                                                               16
Gulberg Residencia                                                  16
G-6                                                                 16
Askari Tower 3                                                      15
Khanna Pul                                                          15
Gulberg Greens - Block A                                            15
Silver Oaks Apartments                                              15
F-11/4                                                              15
DHA Phase 1 - Defence Villas                                        15
Mumtaz City - Chanab Block                                          15
DHA Defence Phase 3                                                 15
Karakoram Diplomatic Enclave                                        14
I-11/2                                                              14
Soan Garden - Block B                                               14
F-6/3                                                               14
Askari Tower 4                                                      14
G-10/4                                                              14
E-16/3                                                              14
E-11/3                                                              13
I-8/4                                                               13
DHA Valley - Oleander Sector                                        13
DHA Phase 1 - Sector F                                              13
Korang Town                                                         13
Bahria Enclave - Sector G                                           13
PWD Housing Society - Block D                                       13
DHA Phase 2 - Sector D                                              12
Diamond Mall & Residency                                            12
Capital Square                                                      12
Chak Shahzad                                                        12
F-6/1                                                               12
E-17/3                                                              12
Tarlai                                                              12
El Cielo                                                            11
I-10/1                                                              11
G-10/1                                                              11
F-10/3                                                              11
Margalla View Housing Society                                       11
Jhangi Syedan                                                       11
G-11/4                                                              11
Top City 1 - Block B                                                11
Bahria Enclave - Sector C2                                          11
Karakoram Greens                                                    11
PWD Housing Society - Block A                                       11
F-17/2                                                              11
F-10/2                                                              11
G-15/1                                                              10
F-7/3                                                               10
Lilly Sector - Block A                                              10
National Police Foundation O-9 - Block C                            10
G-11/1                                                              10
Faisal Hills                                                        10
E-11/1                                                              10
G-10/2                                                              10
F-11/1                                                              10
River Garden                                                        10
Bahria Enclave - Sector C                                           10
The Galleria                                                        10
Naval Anchorage - Block G                                           10
CBR Town Phase 1                                                    10
Oleander Sector - DHA Homes                                         10
Ghauri Town Phase 4A                                                10
Soan Garden - Block D                                                9
Park View City                                                       9
I-14/4                                                               9
Faisal Hills - Executive Block                                       9
G-16/4                                                               9
Emaar Canyon Views                                                   9
Executive Heights                                                    9
DHA Phase 2 - Sector A                                               9
MPCHS - Block D                                                      9
Al-Safa Heights                                                      9
Shah Allah Ditta                                                     9
I-10/2                                                               9
Madina Tower                                                         9
Askari Tower 2                                                       9
G-14                                                                 9
DHA Valley - Lilly Sector                                            8
MPCHS - Block B Extension 1                                          8
Gulshan-e-Sehat 1                                                    8
Warda Hamna Residencia 3                                             8
Defence Executive Apartments                                         8
F-10/1                                                               8
F-10/4                                                               8
Faisal Town Phase 1 - Block B                                        8
Pakistan Town - Phase 2                                              8
Soan Garden - Block E                                                8
F-6/2                                                                8
Lignum Tower                                                         8
Kazani Heights                                                       8
DHA Phase 3 - Block B                                                8
Bahria Enclave - Sector J                                            8
F-11/2                                                               8
Luxus Mall and Residency                                             8
DHA Phase 2 - Sector F                                               8
E-18                                                                 8
Sofia Sapphire                                                       8
G-8/2                                                                7
Park View City - Downtown Block                                      7
MPCHS - Block A                                                      7
Bahria Garden City                                                   7
Gulberg Residencia - Block C                                         7
DHA Phase 1 - Sector B                                               7
Park View - Block H                                                  7
Mall of Islamabad                                                    7
The Royal Mall and Residency                                         7
G-6/3                                                                7
Mumtaz City - Ravi Block                                             7
Al-Ghurair Giga - Block 16                                           7
New Blue Area                                                        7
Blue Area                                                            7
I-14/1                                                               7
PWD Housing Society - Block B                                        7
Gulberg Residencia - Block L                                         7
F-10 Markaz                                                          7
Gulberg Greens - Block B                                             7
DHA Valley                                                           7
I-14/3                                                               7
G-16                                                                 7
11 Central Apartments                                                7
Margalla View Society - Block D                                      6
Lilly Sector - DHA Homes                                             6
Ghauri Town                                                          6
DHA Phase 2 - Sector C                                               6
Faisal Hills - Block A                                               6
DHA Phase 5 - Sector B                                               6
Gulberg Residencia - Block F                                         6
Oleander Sector - Block B                                            6
Zeta-1 Mall                                                          6
F-7/2                                                                6
Bahria Enclave - Sector C3                                           6
I-16                                                                 6
E-16/2                                                               6
National Police Foundation O-9                                       6
Bahria Garden City - Zone 1                                          6
DHA Phase 2 - Sector E                                               6
Top City 1 - Block C                                                 6
G-10/3                                                               6
Thanda Pani                                                          6
CBR Town Phase 1 - Block D                                           5
E-11/2                                                               5
G-15/2                                                               5
Park Enclave 1                                                       5
Gulberg Residencia - Block I                                         5
G-8                                                                  5
Pakistan Town - Phase 1                                              5
Chak Shahzad Farms                                                   5
G-11/2                                                               5
Burma Town                                                           5
Gulberg Greens - Block E                                             5
I-12                                                                 5
Telegardens (T&T ECHS)                                               5
Gulberg Residencia - Block J                                         5
DHA Phase 2 - Sector J                                               5
Gulberg Arena Mall                                                   5
I-11                                                                 5
Al-Ghurair Giga                                                      5
Ghauri Town Phase 5B                                                 5
Marwa Town                                                           5
Park Road                                                            5
Gulshan-e-Sehat 1 - Block D                                          5
G-6/4                                                                5
Simly Dam Road                                                       5
Zaraj Housing Scheme                                                 5
G-14/2                                                               5
Pakistan Town                                                        5
The Magnus                                                           5
Constitution Avenue                                                  4
Pine Heights Luxury Apartments                                       4
DHA Homes                                                            4
F-8/1                                                                4
Bahria Enclave - Sector I                                            4
The Arch                                                             4
Airport Green Garden - Block A                                       4
Robinas Luxury Residences                                            4
Taramrri                                                             4
Elysium Mall                                                         4
Arsalan Town                                                         4
Park Enclave                                                         4
Capital Resorts                                                      4
Gulberg Residencia - D Markaz                                        4
Lehtrar Road                                                         4
G-8/1                                                                4
Islamabad - Murree Expressway                                        4
I-10/4                                                               4
Al-Ghurair Giga - Block 7                                            4

In [15]:
with pd.option_context('display.max_rows', None):
    print(df['Real Location'].value_counts())

Real Location
DHA Defence Phase 2, DHA Defence                                            363
Bani Gala, Islamabad                                                        242
G-13, Islamabad                                                             213
D-12, Islamabad                                                             133
Top City 1, Islamabad                                                       125
B-17, Islamabad                                                             123
F-8, Islamabad                                                              116
Bahria Enclave, Bahria Town                                                 103
F-7, Islamabad                                                               91
MPCHS - Block F, MPCHS - Multi Gardens                                       81
Faisal Town - F-18, Islamabad                                                81
MPCHS - Multi Gardens, B-17                                                  80
F-6, Islamabad                                                               74
G-11, Islamabad                                                              71
E-11, Islamabad                                                              70
F-11, Islamabad                                                              68
Gulberg Greens, Gulberg                                                      65
Faisal Margalla City, B-17                                                   65
Jinnah Gardens, FECHS                                                        64
Bahria Enclave - Sector N, Bahria Enclave                                    62
Bahria Enclave - Sector C1, Bahria Enclave                                   57
The Centaurus, F-8                                                           54
Jinnah Gardens Phase 1, Jinnah Gardens                                       54
Eighteen, Kashmir Highway                                                    52
Soan Garden, Islamabad                                                       51
F-10, Islamabad                                                              49
DHA Defence Phase 5, DHA Defence                                             49
D-17, Islamabad                                                              48
G-13/1, G-13                                                                 44
H-13, Islamabad                                                              44
Top City 1 - Block A, Top City 1                                             44
I-12/1, I-12                                                                 44
MPCHS - Block C, MPCHS - Multi Gardens                                       41
Sukh Chayn Residence, F-10                                                   40
Defence Residency, DHA Defence Phase 2                                       39
Mumtaz City, Islamabad                                                       38
MPCHS - Block B, MPCHS - Multi Gardens                                       38
Faisal Town Phase 1 - Block A, Faisal Town Phase 1                           38
E-7, Islamabad                                                               37
G-13/2, G-13                                                                 37
MPCHS - Block E, MPCHS - Multi Gardens                                       36
G-14/4, G-14                                                                 35
G-11/3, G-11                                                                 35
D-12/4, D-12                                                                 34
Diplomatic Enclave, Islamabad                                                34
I-8/3, I-8                                                                   33
I-16/3, I-16                                                                 33
Askari Heights 4, DHA Phase 5 - Sector H                                     32
D-12/1, D-12                                                                 30
G-9, Islamabad                                                               30
Bahria Enclave - Sector H, Bahria Enclave                                    29
F-17, Islamabad                                                              28
F-11 Markaz, F-11                                                            28
Bahria Enclave - Sector B1, Bahria Enclave                                   28
Cube Apartments, Bahria Enclave                                              27
Oleander Sector - DHA Homes Block A, DHA Valley - Oleander Sector            27
PHAF Officers Residencia, Kuri Road                                          27
Bahria Enclave - Sector A, Bahria Enclave                                    27
Zarkon Heights, G-15                                                         26
Naval Anchorage, Islamabad                                                   25
I-8, Islamabad                                                               25
G-15, Islamabad                                                              25
I-14, Islamabad                                                              24
G-9/3, G-9                                                                   24
DHA Phase 2 - Sector B, DHA Defence Phase 2                                  24
Faisal Town Phase 1 - Block C, Faisal Town Phase 1                           23
G-10, Islamabad                                                              23
Soan Garden - Block H, Soan Garden                                           22
E-11/4, E-11                                                                 22
Top City 1 - Block D, Top City 1                                             22
Faisal Town Phase 1, Faisal Town - F-18                                      21
G-9/4, G-9                                                                   21
Goldcrest Views, DHA Defence Phase 2                                         21
G-9/1, G-9                                                                   21
G-13/3, G-13                                                                 21
Capital Residencia, Margalla Hills-2                                         21
Smama Star Mall & Residency, Gulberg Greens                                  20
PWD Housing Scheme, Islamabad                                                20
DHA Defence Phase 1, DHA Defence                                             20
Bhara kahu, Islamabad                                                        20
DHA Phase 5 - Sector F, DHA Defence Phase 5                                  20
F-8/3, F-8                                                                   19
MPCHS - Block C1, MPCHS - Multi Gardens                                      19
D-12/2, D-12                                                                 18
I-8/2, I-8                                                                   18
DHA Phase 2 - Sector G, DHA Defence Phase 2                                  18
F-11/3, F-11                                                                 18
I-10, Islamabad                                                              18
Skypark One, Gulberg Greens                                                  18
Gulberg Heights, Gulberg Greens                                              18
G-13/4, G-13                                                                 18
D-12/3, D-12                                                                 17
CBR Town Phase 1 - Block C, CBR Town Phase 1                                 17
Gulberg Greens - Block C, Gulberg Greens                                     17
Goldcrest Highlife, DHA Defence Phase 2                                      17
Askari Tower 1, DHA Defence Phase 2                                          17
F-7/1, F-7                                                                   16
Gulberg Residencia, Gulberg                                                  16
G-6, Islamabad                                                               16
Askari Tower 3, DHA Defence Phase 5                                          15
Khanna Pul, Islamabad                                                        15
Gulberg Greens - Block A, Gulberg Greens                                     15
Silver Oaks Apartments, F-10                                                 15
F-11/4, F-11                                                                 15
DHA Phase 1 - Defence Villas, DHA Phase 1 - Sector F                         15
Mumtaz City - Chanab Block, Mumtaz City                                      15
DHA Defence Phase 3, DHA Defence                                             15
Karakoram Diplomatic Enclave, Islamabad                                      14
I-11/2, I-11                                                                 14
Soan Garden - Block B, Soan Garden                                           14
F-6/3, F-6                                                                   14
Askari Tower 4, DHA Defence Phase 5                                          14
G-10/4, G-10                                                                 14
E-16/3, E-16                                                                 14
E-11/3, E-11                                                                 13
I-8/4, I-8                                                                   13
DHA Valley - Oleander Sector, DHA Valley                                     13
DHA Phase 1 - Sector F, DHA Defence Phase 1                                  13
Korang Town, Islamabad                                                       13
Bahria Enclave - Sector G, Bahria Enclave                                    13
PWD Housing Society - Block D, PWD Housing Scheme                            13
DHA Phase 2 - Sector D, DHA Defence Phase 2                                  12
Diamond Mall & Residency, Gulberg Greens                                     12
Capital Square, B-17                                                         12
Chak Shahzad, Islamabad                                                      12
F-6/1, F-6                                                                   12
E-17/3, E-17                                                                 12
Tarlai, Islamabad                                                            12
El Cielo, GT Road                                                            11
I-10/1, I-10                                                                 11
G-10/1, G-10                                                                 11
F-10/3, F-10                                                                 11
Margalla View Housing Society, D-17                                          11
Jhangi Syedan, Islamabad                                                     11
G-11/4, G-11                                                                 11
Top City 1 - Block B, Top City 1                                             11
Bahria Enclave - Sector C2, Bahria Enclave                                   11
Karakoram Greens, Gulberg Greens                                             11
PWD Housing Society - Block A, PWD Housing Scheme                            11
F-17/2, F-17                                                                 11
F-10/2, F-10                                                                 11
G-15/1, G-15                                                                 10
F-7/3, F-7                                                                   10
Lilly Sector - Block A, DHA Valley - Lilly Sector                            10
National Police Foundation O-9 - Block C, National Police Foundation O-9     10
G-11/1, G-11                                                                 10
Faisal Hills, Islamabad                                                      10
E-11/1, E-11                                                                 10
G-10/2, G-10                                                                 10
F-11/1, F-11                                                                 10
River Garden, Islamabad                                                      10
Bahria Enclave - Sector C, Bahria Enclave                                    10
The Galleria, Bahria Enclave                                                 10
Naval Anchorage - Block G, Naval Anchorage                                   10
CBR Town Phase 1, CBR Town                                                   10
Oleander Sector - DHA Homes, DHA Valley - Oleander Sector                    10
Ghauri Town Phase 4A, Ghauri Town                                            10
Soan Garden - Block D, Soan Garden                                            9
Park View City, Islamabad                                                     9
I-14/4, I-14                                                                  9
Faisal Hills - Executive Block, Faisal Hills                                  9
G-16/4, G-16                                                                  9
Emaar Canyon Views, Islamabad                                                 9
Executive Heights, F-11                                                       9
DHA Phase 2 - Sector A, DHA Defence Phase 2                                   9
MPCHS - Block D, MPCHS - Multi Gardens                                        9
Al-Safa Heights, F-11 Markaz                                                  9
Shah Allah Ditta, Islamabad                                                   9
I-10/2, I-10                                                                  9
Madina Tower, E-11                                                            9
Askari Tower 2, DHA Defence Phase 2                                           9
G-14, Islamabad                                                               9
DHA Valley - Lilly Sector, DHA Valley                                         8
MPCHS - Block B Extension 1, MPCHS - Multi Gardens                            8
Gulshan-e-Sehat 1, E-18                                                       8
Warda Hamna Residencia 3, G-11/3                                              8
Defence Executive Apartments, DHA Defence Phase 2                             8
F-10/1, F-10                                                                  8
F-10/4, F-10                                                                  8
Faisal Town Phase 1 - Block B, Faisal Town Phase 1                            8
Pakistan Town - Phase 2, Pakistan Town                                        8
Soan Garden - Block E, Soan Garden                                            8
F-6/2, F-6                                                                    8
Lignum Tower, DHA Defence Phase 2                                             8
Kazani Heights, Islamabad Expressway                                          8
DHA Phase 3 - Block B, DHA Defence Phase 3                                    8
Bahria Enclave - Sector J, Bahria Enclave                                     8
F-11/2, F-11                                                                  8
Luxus Mall and Residency, Gulberg Greens - Block B                            8
DHA Phase 2 - Sector F, DHA Defence Phase 2                                   8
E-18, Islamabad                                                               8
Sofia Sapphire, Mumtaz City                                                   8
G-8/2, G-8                                                                    7
Park View City - Downtown Block, Park View City                               7
MPCHS - Block A, MPCHS - Multi Gardens                                        7
Bahria Garden City, Bahria Town                                               7
Gulberg Residencia - Block C, Gulberg Residencia                              7
DHA Phase 1 - Sector B, DHA Defence Phase 1                                   7
Park View - Block H, Park View City                                           7
Mall of Islamabad, Blue Area                                                  7
The Royal Mall and Residency, Bahria Enclave                                  7
G-6/3, G-6                                                                    7
Mumtaz City - Ravi Block, Mumtaz City                                         7
Al-Ghurair Giga - Block 16, Al-Ghurair Giga                                   7
New Blue Area, Islamabad                                                      7
Blue Area, Islamabad                                                          7
I-14/1, I-14                                                                  7
PWD Housing Society - Block B, PWD Housing Scheme                             7
Gulberg Residencia - Block L, Gulberg Residencia                              7
F-10 Markaz, F-10                                                             7
Gulberg Greens - Block B, Gulberg Greens                                      7
DHA Valley, DHA Defence                                                       7
I-14/3, I-14                                                                  7
G-16, Islamabad                                                               7
11 Central Apartments, G-11/1                                                 7
Margalla View Society - Block D, Margalla View Housing Society                6
Lilly Sector - DHA Homes, DHA Valley - Lilly Sector                           6
Ghauri Town, Islamabad                                                        6
DHA Phase 2 - Sector C, DHA Defence Phase 2                                   6
Faisal Hills - Block A, Faisal Hills                                          6
DHA Phase 5 - Sector B, DHA Defence Phase 5                                   6
Gulberg Residencia - Block F, Gulberg Residencia                              6
Oleander Sector - Block B, DHA Valley - Oleander Sector                       6
Zeta-1 Mall, GT Road                                                          6
F-7/2, F-7                                                                    6
Bahria Enclave - Sector C3, Bahria Enclave                                    6
I-16, Islamabad                                                               6
E-16/2, E-16                                                                  6
National Police Foundation O-9, Islamabad                                     6
Bahria Garden City - Zone 1, Bahria Garden City                               6
DHA Phase 2 - Sector E, DHA Defence Phase 2                                   6
Top City 1 - Block C, Top City 1                                              6
G-10/3, G-10                                                                  6
Thanda Pani, Islamabad                                                        6
CBR Town Phase 1 - Block D, CBR Town Phase 1                                  5
E-11/2, E-11                                                                  5
G-15/2, G-15                                                                  5
Park Enclave 1, Park Enclave                                                  5
Gulberg Residencia - Block I, Gulberg Residencia                              5
G-8, Islamabad                                                                5
Pakistan Town - Phase 1, Pakistan Town                                        5
Chak Shahzad Farms, Chak Shahzad                                              5
G-11/2, G-11                                                                  5
Burma Town, Islamabad                                                         5
Gulberg Greens - Block E, Gulberg Greens                                      5
I-12, Islamabad                                                               5
Telegardens (T&T ECHS), F-17                                                  5
Gulberg Residencia - Block J, Gulberg Residencia                              5
DHA Phase 2 - Sector J, DHA Defence Phase 2                                   5

In [16]:
# Assuming your dataframe is named housing_data
df['Real Location'].str.split(',').str.get(1).str.split(' - ', n=1, expand=True)

                    0     1
0                D-12  None
1                D-12  None
2                D-12  None
3                D-12  None
4      Bahria Enclave  None
...               ...   ...
6478             G-13  None
6479             G-13  None
6480        Islamabad  None
6481   Gulberg Greens  None
6482      Mumtaz City  None

[6463 rows x 2 columns]

### Price
Selecting a common unit

In [18]:
df['Price'].str.split(' ').str.get(1).value_counts()

Price
Crore    5722
Lakh      685
Arab       55
Name: count, dtype: int64

In [19]:
df['Price'].str.split(' ').str.get(0).str[3:].astype('float')

0       12.00
1        5.20
2        4.30
3        5.75
4        2.70
        ...
6478    12.00
6479     5.60
6480    17.00
6481     1.10
6482     3.30
Name: Price, Length: 6463, dtype: float64

In [63]:
df.loc[5379]['Price']

'PKR1'

In [65]:
df.drop(index=5379,inplace=True)

*Error in one row, so removing it*

In [66]:
def Price_to_Cr(series):
    unit = series.strip().split(' ')[1]
    price = float(series.strip().split(' ')[0][3:])
    if (unit =='Lakh'):
        price = price / 100
    elif (unit =='Arab'):
        price = price * 100

    series = price
    return series

In [67]:
df['Price'].iloc[5381:].apply(Price_to_Cr)

5382    36.0
5383     5.8
5384     7.5
5385     3.5
5386     2.3
        ...
6478    12.0
6479     5.6
6480    17.0
6481     1.1
6482     3.3
Name: Price, Length: 1081, dtype: float64

In [68]:
df['Price'] = df['Price'].apply(Price_to_Cr)

In [69]:
df['Price'].sample(10)

5785     6.85
5577     1.15
4495     5.15
5207    60.00
439     75.00
424     23.00
5466     2.00
4415     3.30
3216     4.25
3299     1.35
Name: Price, dtype: float64

In [70]:
df.rename(columns={"Price":'Price(Cr)'},inplace=True)

### Bath(s)
There is '-' category,<br>We can fill it from 'Amenities: Room'

In [71]:
df['Bath(s)'].value_counts()

Bath(s)
6     2059
5      891
2      833
4      741
3      648
7      478
1      467
-      340
10       3
9        1
8        1
Name: count, dtype: int64

In [72]:
df[df['Bath(s)'] == '-']['Amenities: Rooms'].str.split(',').str.get(1).str.split(':').str.get(0).value_counts()

Amenities: Rooms
Bathrooms                 221
Dining Room                38
Servant Quarters            3
Other Rooms                 2
Lounge or Sitting Room      1
Drawing Room                1
Name: count, dtype: int64

In [73]:
df[df['Bath(s)'] == '-']['Amenities: Rooms'].sample(5)

3082    Bedrooms: 2, Bathrooms: 2, Drawing Room, Dinin...
1988    Bedrooms: 9, Bathrooms: 11, Servant Quarters, ...
5116    Bedrooms: 4, Bathrooms: 5, Servant Quarters: 1...
246     Bedrooms: 5, Bathrooms: 6, Servant Quarters: 1...
954     Drawing Room, Dining Room, Study Room, Prayer ...
Name: Amenities: Rooms, dtype: str

<br>

**Will remove those rows where you cannot fill the 'Bath(s)' information from 'Amenities: Room'**

In [74]:
temp = df[df['Bath(s)'] == '-']['Amenities: Rooms'].str.split('Bathrooms').str.get(1).str.split(',').str.get(0).str.strip()
empty_idxs = temp[temp==''].index

In [75]:
temp.sample(5)

4925     NaN
2633     NaN
4358     : 5
2226     NaN
2197    : 10
Name: Amenities: Rooms, dtype: object

In [76]:
empty_idxs

Index([129, 1059, 1587, 4435, 4644, 5411], dtype='int64')

In [77]:
df.drop(index=empty_idxs,inplace=True)

In [78]:
df.shape[0]

6456

### Area
Converting Kanal to Marla. <br>
1 Kanal = 20 Marla

In [79]:
df['Area'].sample(5)

6318    2 Kanal
5729    5 Marla
3967    8 Marla
3390    1 Kanal
342     1 Kanal
Name: Area, dtype: str

In [80]:
# No other unit for Area
df['Area'].str.split().str.get(1).value_counts()

Area
Marla    4941
Kanal    1515
Name: count, dtype: int64

In [81]:
def Areaunitconverter(series):
    unit = series.split()[1].strip()
    no = float(series.split()[0])
    if unit == 'Kanal':
        no *= 20

    return no

In [82]:
df['Area'].apply(Areaunitconverter).tail(5)

6478    20.0
6479     8.0
6480    20.0
6481     2.4
6482     8.0
Name: Area, dtype: float64

In [83]:
df['Area'].tail(5)

6478      1 Kanal
6479      8 Marla
6480      1 Kanal
6481    2.4 Marla
6482      8 Marla
Name: Area, dtype: str

In [84]:
df['Area'] = df['Area'].apply(Areaunitconverter)

In [85]:
df.rename(columns={'Area':'Area(Marla)'},inplace=True)

### Location
Remove the part 'Islamabad, Islmabad Capital' since it is the same every where.

In [86]:
df['Location']

0              D-12, Islamabad, Islamabad Capital
1              D-12, Islamabad, Islamabad Capital
2              D-12, Islamabad, Islamabad Capital
3              D-12, Islamabad, Islamabad Capital
4       Bahria Town, Islamabad, Islamabad Capital
                          ...
6478           G-13, Islamabad, Islamabad Capital
6479           G-13, Islamabad, Islamabad Capital
6480           G-13, Islamabad, Islamabad Capital
6481        Gulberg, Islamabad, Islamabad Capital
6482    Mumtaz City, Islamabad, Islamabad Capital
Name: Location, Length: 6456, dtype: str

In [87]:
df['Location'].str.split(',',n=1).str.get(1).value_counts()

Location
Islamabad, Islamabad Capital    6456
Name: count, dtype: int64

In [88]:
pd.set_option('display.max_rows', None)

In [89]:
df['Location'].str.split(',').str.get(0).value_counts().sort_index()

Location
Airport Enclave                                6
Al Qaim Town                                   1
Alipur Farash                                  1
Arsalan Town                                   4
B-17                                         521
Bahria Town                                  430
Bani Gala                                    246
Bhara kahu                                    21
Blue Area                                     18
Burma Town                                     5
C-18                                           1
CBR Town                                      42
Canyon Views Cvrp                              2
Chak Shahzad                                  17
Chatha Bakhtawar                               3
Constitution Avenue                            8
D-12                                         235
D-17                                          76
D-18                                           3
DHA Defence                                  938
Diplomatic Enclave                            34
E-11                                         162
E-12                                           1
E-16                                          29
E-17                                          12
E-18                                          26
E-7                                           37
Emaar Canyon Views                            10
F-10                                         151
F-11                                         172
F-15                                           4
F-17                                          45
F-6                                          111
F-7                                          126
F-8                                          196
FECHS                                        119
FOECHS - Foreign Office Employees Society      1
Faisal Hills                                  26
Faisal Town - F-18                           170
Fateh Jang Road                                2
G-10                                          68
G-11                                         158
G-12                                           1
G-13                                         334
G-14                                          50
G-15                                          75
G-16                                          19
G-6                                           29
G-7                                            2
G-8                                           17
G-9                                           99
GT Road                                       20
Gandhara City                                  2
Ghauri Town                                   42
Golra Mor                                      1
Green Avenue                                   3
Gulberg                                      289
H-12                                           1
H-13                                          50
I-10                                          44
I-11                                          21
I-12                                          49
I-13                                           2
I-14                                          47
I-16                                          42
I-8                                           93
I-9                                            8
Islamabad - Murree Expressway                  5
Islamabad Expressway                          12
Japan Road                                     1
Jhangi Syedan                                 11
Karakoram Diplomatic Enclave                  14
Karakoram Enclave 1                            2
Kashmir Highway                               61
Khanna Pul                                    15
Koral Town                                     1
Korang Town                                   13
Kuri Road                                     28
Lehtrar Road                                   6
Madina Town                                    1
Main Margalla Road                             2
Malot                                          1
Margalla Town                                  2
Marwa Town                                     5
Meherban Colony                                1
Mid City                                       1
Multi Residencia & Orchards                    2
Mumtaz City                                   70
Murree Road                                    1
National Police Foundation                     1
National Police Foundation O-9                21
Naval Anchorage                               45
New Blue Area                                  6
Orchard Scheme                                 4
PAF Tarnol                                     2
PECHS                                          7
PWD Housing Scheme                            55
PWD Road                                       1
Pakistan Town                                 18
Park Enclave                                   9
Park Road                                      5
Park View City                                28
Phulgran                                       1
Pir Sohawa                                     6
Rawal Enclave                                  1
River Garden                                  10
Sehala Farm House                              1
Shah Allah Ditta                               9
Shaheen Town                                   4
Shehzad Town                                   2
Sihala                                         1
Simly Dam Road                                 6
Soan Garden                                  113
Taramrri                                       4
Tarlai                                        12
Tarnol                                         6
Thalian                                        1
Thanda Pani                                    6
Top City 1                                   219
University Town                                4
Zaraj Housing Scheme                          15
Name: count, dtype: int64

In [90]:
df['Location'] = df['Location'].str.split(',').str.get(0).str.strip()

In [91]:
df.info()

<class 'pandas.DataFrame'>
Index: 6456 entries, 0 to 6482
Data columns (total 15 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Real Location                                     6456 non-null   str
 1   Type                                              6456 non-null   str
 2   Price(Cr)                                         6456 non-null   float64
 3   Bath(s)                                           6456 non-null   str
 4   Area(Marla)                                       6456 non-null   float64
 5   Bedroom(s)                                        6456 non-null   str
 6   Location                                          6456 non-null   object
 7   Description                                       6456 non-null   str
 8   Amenities: Main Features                          5997 non-null   str
 9   Amenities: Rooms                                  5834 non-null   str
 10  Amenities: Business and Communication             5643 non-null   str
 11  Amenities: Community Features                     5599 non-null   str
 12  Amenities: Healthcare Recreational                5045 non-null   str
 13  Amenities: Nearby Locations and Other Facilities  6027 non-null   str
 14  Amenities: Other Facilities                       5640 non-null   str
dtypes: float64(2), object(1), str(12)
memory usage: 9.4+ MB

In [92]:
df['Amenities: Rooms'].iloc[0]

'Bedrooms: 6, Bathrooms: 8, Servant Quarters: 2, Drawing Room, Dining Room, Kitchens: 2, Study Room, Prayer Room, Powder Room, Gym, Store Rooms: 1, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms'

In [93]:
df['Amenities: Main Features'].iloc[1]

'Built in year, Parking Spaces: 3, Double Glazed Windows, Central Air Conditioning, Central Heating, Flooring, Electricity Backup, Waste Disposal, Floors: 2, Other Main Features'

In [94]:
df.to_csv('zameen_new_cleaned_v1.csv')