# Outline

Will be using *Iterative or KNN Imputer* to fill the missing values

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
houses = pd.read_csv('C:/Users/Wajih/Work (DataScience)/CAPSTONE PROJECTS/Real Estate Project/Zameen.com/3. Outlier Detection/houses_outlier_handled_new.csv',index_col=0)

In [3]:
houses.columns

Index(['Main Location', 'Price(Cr)', 'Bath(s)', 'Area(Marla)', 'Bedroom(s)',
       'Description', 'Amenities: Main Features', 'Amenities: Rooms',
       'Amenities: Healthcare Recreational', 'Amenities: Other Facilities',
       'IsPrimeLoc', 'SolarInstalled', 'WaterBore', 'CornerHouse',
       'luxury_type', 'Built in year', 'Parking Spaces', 'Floor', 'Bedrooms',
       'Bathrooms', 'Servant Quarters', 'Kitchens', 'Store Rooms',
       'Swimming Pool', 'Storey Unit', 'BedBath_Diff'],
      dtype='object')

In [4]:
# First we remove the featuress we dont need

cols_to_remove = [
    
    'Parking Spaces','Amenities: Main Features', 'Amenities: Rooms',
    'Amenities: Healthcare Recreational',
    'Amenities: Other Facilities','Swimming Pool']

houses.drop(columns=cols_to_remove,inplace = True)

In [5]:
houses.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4383 entries, 0 to 6482
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Main Location     4383 non-null   object
 1   Price(Cr)         4383 non-null   float64
 2   Bath(s)           4298 non-null   float64
 3   Area(Marla)       4383 non-null   float64
 4   Bedroom(s)        4308 non-null   float64
 5   Description       4383 non-null   object
 6   IsPrimeLoc        4383 non-null   bool
 7   SolarInstalled    4383 non-null   bool
 8   WaterBore         4383 non-null   bool
 9   CornerHouse       4383 non-null   bool
 10  luxury_type       4383 non-null   int64
 11  Built in year     3346 non-null   float64
 12  Floor             3256 non-null   float64
 13  Bedrooms          3796 non-null   float64
 14  Bathrooms         3793 non-null   float64
 15  Servant Quarters  2931 non-null   float64
 16  Kitchens          3524 non-null   float64
 17  Store Rooms       2811 non-null   float64
 18  Storey Unit       3631 non-null   float64
 19  BedBath_Diff      4297 non-null   float64
dtypes: bool(4), float64(13), int64(1), object(2)
memory usage: 599.2+ KB

In [6]:
houses.isnull().sum()

Main Location          0
Price(Cr)              0
Bath(s)               85
Area(Marla)            0
Bedroom(s)            75
Description            0
IsPrimeLoc             0
SolarInstalled         0
WaterBore              0
CornerHouse            0
luxury_type            0
Built in year       1037
Floor               1127
Bedrooms             587
Bathrooms            590
Servant Quarters    1452
Kitchens             859
Store Rooms         1572
Storey Unit          752
BedBath_Diff          86
dtype: int64

- Bedroom(s) and Bath(s) --> Fill from Bathrooms and Bedrooms, then use Multivariate Approach
- Built in Year --> Fill from Location
- Storey Unit --> Fill from Floor, then use Multivariate approach
- Kitchens --> Can fill from Floor
- Store room & Servant Quarters --> Use Multivariate Approach

### Bedroom(s) & Bath(s)

In [7]:
houses[(houses['Bath(s)'].isnull())|(houses['Bedroom(s)'].isnull())][['Bathrooms','Bedrooms','Area(Marla)','Storey Unit','Floor','Bath(s)','Bedroom(s)']]

,Bathrooms,Bedrooms,Area(Marla),Storey Unit,Floor,Bath(s),Bedroom(s)
79,NaN,NaN,24.0,2.0,NaN,NaN,7.0
115,NaN,NaN,4.4,NaN,NaN,NaN,NaN
116,NaN,NaN,4.4,NaN,NaN,NaN,NaN
128,NaN,NaN,10.0,NaN,NaN,NaN,NaN
267,NaN,NaN,9.3,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...
5664,NaN,NaN,26.0,NaN,NaN,NaN,NaN
6030,NaN,NaN,15.0,1.0,NaN,NaN,NaN
6033,NaN,NaN,9.3,2.0,NaN,NaN,NaN
6065,NaN,NaN,7.0,2.0,NaN,NaN,NaN
6110,NaN,NaN,7.0,NaN,NaN,NaN,NaN

In [8]:
houses[(houses['Bath(s)'].isnull()) & (houses['Bedroom(s)'].isnull())].shape

(74, 20)

*Removing the rows where both Bath(s) & Bedroom(s) are null*

In [9]:
houses.dropna(subset=['Bath(s)','Bedroom(s)'],inplace=True)

In [10]:
houses.shape

(4297, 20)

In [11]:
houses.isnull().sum()

Main Location          0
Price(Cr)              0
Bath(s)                0
Area(Marla)            0
Bedroom(s)             0
Description            0
IsPrimeLoc             0
SolarInstalled         0
WaterBore              0
CornerHouse            0
luxury_type            0
Built in year        957
Floor               1046
Bedrooms             502
Bathrooms            505
Servant Quarters    1368
Kitchens             775
Store Rooms         1486
Storey Unit          685
BedBath_Diff           0
dtype: int64

### Storey Unit

*How to impute values for Storey Unit?*
- First fill from floor
- If Floor is Nan, use Multivariate approach

In [12]:
houses[(houses['Storey Unit'].isnull()) & ~(houses['Floor'].isnull())].shape

(0, 20)

*Cannot fill from Floor because where there is Nan value for Storey Unit, the corresponding value for Floor is also Nan <br> Using Multivariate Approach*

*Removing Bedrooms, Bathrooms, Floor, BedBath_Diff*

In [13]:
houses.drop(columns=['BedBath_Diff','Floor', 'Bedrooms',
       'Bathrooms'],inplace=True)

In [14]:
houses.isnull().sum()

Main Location          0
Price(Cr)              0
Bath(s)                0
Area(Marla)            0
Bedroom(s)             0
Description            0
IsPrimeLoc             0
SolarInstalled         0
WaterBore              0
CornerHouse            0
luxury_type            0
Built in year        957
Servant Quarters    1368
Kitchens             775
Store Rooms         1486
Storey Unit          685
dtype: int64

### Built in Year

1. First of all we are going to convert the Year column to Category.
2. Then fill the missing values based on Main Location

In [15]:
houses['Built in year'].value_counts()

Built in year
2025.0    1740
2024.0     529
2023.0     203
2022.0     114
2020.0     112
2015.0      82
2021.0      68
2018.0      61
2000.0      53
2010.0      52
2016.0      38
2026.0      37
2019.0      34
2017.0      31
2012.0      22
2005.0      22
2014.0      21
1990.0      17
1998.0      12
1999.0      12
2002.0      10
2013.0       9
2009.0       8
2008.0       8
2001.0       7
1995.0       5
2011.0       4
2027.0       3
1985.0       3
1997.0       3
1988.0       2
2055.0       2
2007.0       2
1992.0       2
2006.0       1
1978.0       1
1980.0       1
2003.0       1
2029.0       1
1982.0       1
1981.0       1
2028.0       1
1970.0       1
1984.0       1
1987.0       1
2004.0       1
Name: count, dtype: int64

In [16]:
houses.groupby('Built in year')['Price(Cr)'].mean().sort_index()

Built in year
1970.0     4.900000
1978.0    24.990000
1980.0    43.000000
1981.0    30.000000
1982.0    70.000000
1984.0    30.000000
1985.0    18.216667
1987.0     3.850000
1988.0    11.000000
1990.0    22.544118
1992.0    55.000000
1995.0    21.700000
1997.0    14.000000
1998.0    22.500000
1999.0    24.410000
2000.0    19.682642
2001.0    17.714286
2002.0    23.100000
2003.0    19.500000
2004.0     1.450000
2005.0    18.595455
2006.0    33.000000
2007.0     5.300000
2008.0    23.031250
2009.0    32.456250
2010.0    13.506731
2011.0    13.287500
2012.0    19.009091
2013.0     8.716667
2014.0    12.596667
2015.0    10.376707
2016.0     7.560000
2017.0     8.733226
2018.0     9.402951
2019.0     7.278824
2020.0    10.133036
2021.0     8.453088
2022.0    11.127544
2023.0    11.032842
2024.0     8.999168
2025.0     7.830756
2026.0     8.864324
2027.0     3.066667
2028.0     8.550000
2029.0     4.850000
2055.0     4.275000
Name: Price(Cr), dtype: float64

- Future --> $>2025$
- Immediate / Brand New --> $2025$
- Recently Built --> $2020 - 2024$
- Modern Era --> $2010 - 2019$
- Established --> $2000 - 2009$
- Vintage / Legacy-- > $< 2000$

In [17]:
# Converting 

bins = [-float('inf'),1999,2009,2019,2024,2025,float('inf')]
labels = ['Vintage','Established','Modern Era','Recently Built','Brand New (2025)','Future']

houses['Property era'] =  pd.cut(houses['Built in year'],bins=bins,labels=labels)

In [18]:
houses['Property era'].value_counts()

Property era
Brand New (2025)    1740
Recently Built      1026
Modern Era           354
Established          113
Vintage               63
Future                44
Name: count, dtype: int64

In [19]:
houses.groupby('Property era')['Price(Cr)'].mean().sort_index()

C:\Users\Wajih\AppData\Local\Temp\ipykernel_19924\4284728181.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  houses.groupby('Property era')['Price(Cr)'].mean().sort_index()

Property era
Vintage             23.651746
Established         20.493186
Modern Era          10.583729
Recently Built       9.725611
Brand New (2025)     7.830756
Future               8.162045
Name: Price(Cr), dtype: float64

In [20]:
houses.groupby('Property era')['Area(Marla)'].mean().sort_index()

C:\Users\Wajih\AppData\Local\Temp\ipykernel_19924\546733391.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  houses.groupby('Property era')['Area(Marla)'].mean().sort_index()

Property era
Vintage             21.861905
Established         20.868142
Modern Era          14.251130
Recently Built      13.111111
Brand New (2025)    11.271552
Future              10.629545
Name: Area(Marla), dtype: float64

*Old properties have greater prices on average, than the new properties. One reason could be that old properties had greater land rather than the New ones.*

In [21]:
houses[houses['Property era'].isnull()]['Main Location'].unique()

array(['D-12', 'FECHS', 'Faisal Town Phase 1', 'D-17', 'G-9',
       'Ghauri Town', 'Bani Gala', 'F-8', 'Margalla Town', 'B-17',
       'Mumtaz City', 'DHA Phase 1', 'DHA Valley', 'I-8', 'H-13',
       'DHA Phase 2', 'Bahria Town', 'I-10', 'Gulberg Residencia', 'G-15',
       'G-13', 'F-7', 'Bahria Enclave', 'DHA Phase 5', 'F-10', 'F-11',
       'Khanna Pul', 'Jhangi Syedan', 'MPCHS - Multi Gardens', 'E-18',
       'I-14', 'G-8', 'G-11', 'PWD Housing Scheme', 'F-17', 'Kuri Road',
       'Naval Anchorage', 'Taramrri', 'F-6', 'Soan Garden', 'G-10',
       'Pakistan Town', 'G-16', 'G-12', 'Top City 1', 'Burma Town',
       'Pir Sohawa', 'Tarnol', 'Faisal Hills', 'G-14', 'Korang Town',
       'Shah Allah Ditta', 'Kashmir Highway', 'Park View City',
       'Bhara kahu', 'I-11', 'G-6', 'I-16', 'Bahria Garden City',
       'Airport Enclave', 'E-11', 'Park Road', 'CBR Town Phase 1',
       'Jinnah Gardens', 'River Garden', 'E-16', 'Emaar Canyon Views',
       'Lehtrar Road', 'Margalla View Housing Society',
       'National Police Foundation O-9', 'Thanda Pani',
       'Airport Green Garden', 'Sihala', 'E-7', 'DHA Phase 3',
       'Madina Town', 'Simly Dam Road', 'Green Avenue', 'Malot', 'PECHS',
       'I-9', 'PAF Tarnol', 'Shaheen Town', 'Tarlai', 'Thalian', 'E-17',
       'D-18'], dtype=object)

In [22]:
houses.groupby("Main Location")['Property era'].count().sort_values()

Main Location
G-12                0
Sihala              0
Thalian             0
PAF Tarnol          0
Park Road           0
                 ...
Bani Gala         172
D-12              189
Bahria Enclave    210
G-13              259
DHA Phase 2       362
Name: Property era, Length: 113, dtype: int64

In [23]:
houses.head(1)

,Main Location,Price(Cr),Bath(s),Area(Marla),Bedroom(s),Description,IsPrimeLoc,SolarInstalled,WaterBore,CornerHouse,luxury_type,Built in year,Servant Quarters,Kitchens,Store Rooms,Storey Unit,Property era
0,D-12,12.0,7.0,10.0,6.0,10 MARLA LUXXARY BRAND NEW PARK FACE AVAILABLE...,False,False,False,False,0,2025.0,2.0,2.0,1.0,2.0,Brand New (2025)

In [24]:
def impute_propert_era(row):
    if pd.isna(row['Property era']):
        mode_location = houses[(houses['Main Location'] == row['Main Location'])]['Property era'].mode()

        if not mode_location.empty:
            return mode_location.iloc[0]
        else:
            return np.nan

    else:
        return row['Property era']

In [25]:
houses.apply(impute_propert_era,axis=1)

0       Brand New (2025)
1       Brand New (2025)
2       Brand New (2025)
3       Brand New (2025)
4       Brand New (2025)
              ...
6472    Brand New (2025)
6478          Modern Era
6479          Modern Era
6480    Brand New (2025)
6482              Future
Length: 4297, dtype: object

In [26]:
location_modes =  houses.groupby('Main Location')['Property era'].apply(lambda x : x.mode().iloc[0] if not x.mode().empty else np.nan )

In [27]:
location_modes

Main Location
Airport Enclave         Brand New (2025)
Airport Green Garden    Brand New (2025)
Al Qaim Town              Recently Built
Alipur Farash           Brand New (2025)
Arsalan Town            Brand New (2025)
                              ...
Thalian                              NaN
Thanda Pani                  Established
Top City 1              Brand New (2025)
University Town           Recently Built
Zaraj Housing Scheme          Modern Era
Name: Property era, Length: 113, dtype: object

In [28]:
houses['Main Location'].nunique()

113

In [29]:
houses['Main Location'].map(location_modes)

0       Brand New (2025)
1       Brand New (2025)
2       Brand New (2025)
3       Brand New (2025)
4       Brand New (2025)
              ...
6472    Brand New (2025)
6478    Brand New (2025)
6479    Brand New (2025)
6480    Brand New (2025)
6482      Recently Built
Name: Main Location, Length: 4297, dtype: object

In [30]:
houses['Property era'] =  houses['Property era'].fillna(houses['Main Location'].map(location_modes))

In [31]:
houses['Property era'].isnull().sum()

np.int64(13)

In [32]:
# Filling the value with the mode now

houses['Property era'] = houses['Property era'].fillna(houses['Property era'].mode()[0])

In [33]:
# Removing Built in Year
houses.drop(columns='Built in year',inplace=True)

In [34]:
houses.isnull().sum()

Main Location          0
Price(Cr)              0
Bath(s)                0
Area(Marla)            0
Bedroom(s)             0
Description            0
IsPrimeLoc             0
SolarInstalled         0
WaterBore              0
CornerHouse            0
luxury_type            0
Servant Quarters    1368
Kitchens             775
Store Rooms         1486
Storey Unit          685
Property era           0
dtype: int64

In [46]:
# Saving the file for Streamlit purposes, will move it later
houses.to_csv('houses.csv')

### Servant Quarters, Kitchens, Store Rooms, Storey Unit

Using Iterative Imputer(Tree based model) to fill the missing values because we haven't scaled our data.

Making a pipeline and doing a Randomized Search CV to find the best hyper parameters for imputing the values.

In [47]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer,SimpleImputer,KNNImputer

from sklearn.ensemble import RandomForestRegressor,ExtraTreesRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.model_selection import RandomizedSearchCV,GridSearchCV

from sklearn import set_config

set_config(transform_output='pandas')

In [48]:
cols_to_impute = ['Bath(s)', 'Area(Marla)', 'Bedroom(s)','Servant Quarters', 'Kitchens', 'Store Rooms','Storey Unit']

In [49]:
trf_simple_imputer = ColumnTransformer(
    [
        ('SimpleImputer',SimpleImputer(),cols_to_impute)
    ],
    remainder='passthrough',verbose_feature_names_out=False
)

trf_iter_imputer = ColumnTransformer(
    [
        ('IterImputer',IterativeImputer(estimator=ExtraTreesRegressor(n_estimators=100, max_depth=10, random_state=42)),cols_to_impute)
    ],
    remainder='passthrough',verbose_feature_names_out=False
)

trf_knn_imputer = ColumnTransformer(
    [
        ('KnnImputer',KNNImputer(),cols_to_impute)
    ],
    remainder='passthrough',verbose_feature_names_out=False
)

In [38]:
final_pipeline = Pipeline(
    [
        ('Impute',None),
        ('Model',XGBRegressor(n_estimators=100))
    ]
)

In [39]:
param_grid = [
    {
        "Impute":[trf_simple_imputer],
        'Impute__SimpleImputer__strategy':['mean','most_frequent']
    },
    {
        "Impute":[trf_iter_imputer],
        "Impute__IterImputer__max_iter":[10,20,30],
        "Impute__IterImputer__n_nearest_features": [3, 5, 10],
        "Impute__IterImputer__imputation_order":['random','ascending','arabic']
    },
    {
        "Impute":[trf_knn_imputer],
        "Impute__KnnImputer__n_neighbors":[10,20,30],
        "Impute__KnnImputer__weights":['distance',"uniform"]
    }
    
]

In [40]:
from sklearn.model_selection import train_test_split

X = houses[['Bath(s)', 'Area(Marla)', 'Bedroom(s)','Servant Quarters', 'Kitchens', 'Store Rooms','Storey Unit']]
y = houses['Price(Cr)']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [ ]:
search_cv = RandomizedSearchCV(final_pipeline,param_grid,n_iter=20,scoring='r2',n_jobs=-1,cv=5,)

search_cv.fit(X_train,y_train)

In [ ]:
search_cv.best_score_

In [ ]:
search_cv.best_estimator_

In [ ]:
results = pd.DataFrame(search_cv.cv_results_)

In [ ]:
results.sort_values(by=['mean_test_score'],ascending=False)[['mean_test_score', 'std_test_score','split0_test_score',
       'split1_test_score', 'split2_test_score', 'split3_test_score',
       'split4_test_score']]

In [ ]:
search_cv.best_params_

In [41]:
trf_best_imputer = ColumnTransformer(
    [
        ('Iter',KNNImputer(weights='uniform',n_neighbors=30),cols_to_impute)
    ],
    remainder='passthrough',verbose_feature_names_out=False,n_jobs=-1
)

best_pipeline =Pipeline(
    [
        ('Impute',trf_best_imputer),
        ('Model',XGBRegressor(n_estimators=100,n_jobs=-1))
    ]
)

In [42]:
best_pipeline.fit(X_train,y_train)

Pipeline(steps=[('Impute',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('Iter',
                                                  KNNImputer(n_neighbors=30),
                                                  ['Bath(s)', 'Area(Marla)',
                                                   'Bedroom(s)',
                                                   'Servant Quarters',
                                                   'Kitchens', 'Store Rooms',
                                                   'Storey Unit'])],
                                   verbose_feature_names_out=False)),
                ('Model',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, cols...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=100, n_jobs=-1,
                              num_parallel_tree=None, ...))])

In [43]:
from sklearn.metrics import r2_score,mean_absolute_error

y_pred = best_pipeline.predict(X_test)
print('R2 Score',r2_score(y_test,y_pred))
print('Mean Absolute Error',mean_absolute_error(y_test,y_pred))

R2 Score 0.7256260506845067
Mean Absolute Error 2.9700130531611872

In [44]:
# Using KNN Imputer to Fill the Missing Values

In [107]:
houses.columns

Index(['Main Location', 'Price(Cr)', 'Bath(s)', 'Area(Marla)', 'Bedroom(s)',
       'Description', 'IsPrimeLoc', 'SolarInstalled', 'WaterBore',
       'CornerHouse', 'luxury_type', 'Servant Quarters', 'Kitchens',
       'Store Rooms', 'Storey Unit', 'Property era'],
      dtype='str')

In [131]:
from sklearn.model_selection import train_test_split

X = houses[['Main Location', 'Bath(s)', 'Area(Marla)', 'Bedroom(s)',
        'IsPrimeLoc', 'SolarInstalled', 'WaterBore',
       'CornerHouse', 'luxury_type', 'Servant Quarters', 'Kitchens',
       'Store Rooms', 'Storey Unit', 'Property era']]
y = houses['Price(Cr)']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [132]:
X_train = round(trf_best_imputer.fit_transform(X_train))

X_test = round(trf_best_imputer.transform(X_test))

In [133]:
X_train.shape

(2878, 14)

In [134]:
X_train.isnull().sum()

Bath(s)             0
Area(Marla)         0
Bedroom(s)          0
Servant Quarters    0
Kitchens            0
Store Rooms         0
Storey Unit         0
Main Location       0
IsPrimeLoc          0
SolarInstalled      0
WaterBore           0
CornerHouse         0
luxury_type         0
Property era        0
dtype: int64

In [136]:
X_test.isnull().sum()

Bath(s)             0
Area(Marla)         0
Bedroom(s)          0
Servant Quarters    0
Kitchens            0
Store Rooms         0
Storey Unit         0
Main Location       0
IsPrimeLoc          0
SolarInstalled      0
WaterBore           0
CornerHouse         0
luxury_type         0
Property era        0
dtype: int64

In [137]:
# Saving X_train, X_test, y_train, y_test

In [138]:
X_train.to_csv('Houses/X_train.csv')
X_test.to_csv('Houses/X_test.csv')
y_train.to_csv('Houses/y_train.csv')
y_test.to_csv('Houses/y_test.csv')